### ISSUE TITLE
Style in incorrect in timeline

### ISSUE THREAD

**Issue by mika-s** [StylishThemes/StackOverflow-Dark#102]
The contrast between the text and the background is pretty poor when in a post's timeline. Some of it also has a light background. [Here](https://i.imgur.com/DQTOOPW.png) is an example. And [here](https://stackoverflow.com/posts/48343642/timeline) is the URL if you want to see for yourself.

**Comment by Mottie** [comment]
Hi @mika-s!

Thanks for reporting this problem, I'll have it fixed shortly.
