### ISSUE TITLE
Filtered Questions doesn't have a dark theme

### ISSUE THREAD

**Issue by mika-s** [StylishThemes/StackOverflow-Dark#103]
I found a partially unstyled page on the StackExchange [Filtered Questions](https://stackexchange.com/filters/) page. I uploaded a screenshot of it to [imgur](https://i.imgur.com/jMbhMpc.png).

**Comment by Mottie** [comment]
Hi @mika-s!

Thanks for reporting this problem. It'll be fixed shortly.
