### ISSUE TITLE
Styling in Meta profile and data explorer

### ISSUE THREAD

**Issue by mika-s** [StylishThemes/StackOverflow-Dark#104]
I found two more places where the dark theme doesn't work.

First is the meta user profile page. Screenshot [here](https://i.imgur.com/5iNJIEv.png). The background for the div containing reputation is white. You can get to the meta user profile by going to your SO profile and then click on *Meta User*.

The second is the data explorer page. Screenshot [here](https://i.imgur.com/yiEFpOT.png). The syntax highlighting isn't using the dark theme and the table has white rows. There is also some white stuff that only shows when the captcha is active. [Here](http://data.stackexchange.com/stackoverflow/query/466/most-controversial-posts-on-the-site) is the URL.

**Comment by Mottie** [comment]
Hi @mika-s!

Thanks for reporting this problem. It'll be fixed shortly.
