### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/StackOverflow-Dark#108]
Zi scrollbar is not styled. 😸

**Comment by VladimirDev93** [comment]
@Mottie Yes, it means "the scrollbar".

I know it can be only styled in Chrome as Firefox strictly uses the system theme for scrollbars, buttons, etc.
However, the scrollbar is not style in Chrome,

Here's the proof.
![untitled](https://user-images.githubusercontent.com/12301022/39972144-007d5ca4-5709-11e8-9fb0-9e9dcef6b45a.png)

**Comment by Mottie** [comment]
Done 😸

**Comment by VladimirDev93** [comment]
@Mottie Gracias! :smile_cat:
