### ISSUE TITLE
It was working fine until... 

### ISSUE THREAD

**Issue by IGRACH** [StylishThemes/StackOverflow-Dark#11]
It was working fine until white background started to show up on questions and answers. Windows 7 64bit Chrome Version 39.0.2171.99 m
![1](https://cloud.githubusercontent.com/assets/7463331/5770442/b973e288-9d2a-11e4-80ff-7cecf139a279.jpg)

Great theme BTW, could not use stackoverflow without it xD

**Comment by Mottie** [comment]
Hi @IGRACH!

Wow, that must have just happened... I was just using SO about an hour ago.

Thanks for reporting it, I'll see what I can do.

**Comment by IGRACH** [comment]
Thanks for feed back, It's the same with other themes. I'm guessing they are doing something on the site.

**Comment by Mottie** [comment]
Ok, should be all fixed ([ref](https://github.com/StylishThemes/StackOverflow-Dark/commit/cfdcb4420e1f501912f861edf69a44be54a88007))!
