### ISSUE TITLE
looks terrible on the salary calculator page ( https://stackoverflow.com/company/salary/calculator )

### ISSUE THREAD

**Issue by divinity76** [StylishThemes/StackOverflow-Dark#110]
this page https://stackoverflow.com/company/salary/calculator
looks like this: 
![image](https://user-images.githubusercontent.com/1874996/40415522-577d83f2-5e7b-11e8-8cb4-4545c530ccc1.png)

that looks wrong to me.

**Comment by Mottie** [comment]
Hi @divinity76!

Thanks for letting us know, it's all fixed.
