### ISSUE TITLE
Python code snippets in accepted answer are hard to read

### ISSUE THREAD

**Issue by mxr** [StylishThemes/StackOverflow-Dark#118]
See https://stackoverflow.com/a/231855/379420 and the screenshot for an example. Would it be possible to avoid changing the div's background in this case?

![image](https://user-images.githubusercontent.com/252209/44103719-fd53d2c4-9fba-11e8-8251-9785dde6934d.png)

The selector for the screenshotted code block is `#answer-41426583 > div > div.answercell.post-layout--right > div.post-text > pre:nth-child(2)`

**Comment by RaitaroH** [comment]
In waterfox:
![screenshot_20180814_200639](https://user-images.githubusercontent.com/19552720/44106526-9352a60a-9ffd-11e8-8ab4-878b0b43d424.png)

In firefox:
![screenshot_20180814_200805](https://user-images.githubusercontent.com/19552720/44106604-ca34ab00-9ffd-11e8-9270-351796afd8a2.png)

**Comment by Mottie** [comment]
Hi @mxr!

This really depends on the selected syntax theme; but maybe it would be a better idea to leave the accepted answer code background color alone.

**Comment by RaitaroH** [comment]
@Mottie the syntax is not the cause. Waterfox aside, in Firefox the syntax changes to colored text. The rest of the text is white. In his case the white text is the issue thus not a the syntax.

**Comment by Mottie** [comment]
Green code blocks removed in https://github.com/StylishThemes/StackOverflow-Dark/commit/5be081066955a75d3f487b243509384c83a98336 - please update to v2.11.21 to test it.

**Comment by RaitaroH** [comment]
@Mottie I think it looks worse but alas.

**Comment by Mottie** [comment]
Can't make everyone happy 😿

**Comment by Mottie** [comment]
Hmm, actually... I was a bit too aggressive on removing that entire block.

**Comment by mxr** [comment]
Thanks, 2.11.22 is a lot more readable. My repro is on Chrome Version 67.0.3396.99 FWIW.

On 2.11.22 there is some additional gray character highlighting that would be nice to remove but overall 2.11.22 is great! Thanks!

![image](https://user-images.githubusercontent.com/252209/44109910-4aafb388-9fcc-11e8-9d83-10d578943784.png)

(selector for that first `>` is `#answer-231855 > div > div.answercell.post-layout--right > div.post-text > pre:nth-child(44) > code > span:nth-child(1)`)

**Comment by the-j0k3r** [comment]
Some buttons are now broken but this is how it looks here.

![screenshot_2018-08-14 what does the yield keyword do](https://user-images.githubusercontent.com/31389848/44111983-c457b0d0-9ffb-11e8-8286-df6f60e6b2f9.png)

**Comment by the-j0k3r** [comment]
bah, now in 2.11.22 it looks crap no matter what syntax style because all lines also have a background.

![capture](https://user-images.githubusercontent.com/31389848/44112578-51122a36-9ffd-11e8-9199-0b8bd1679bf0.PNG)

Some styles this is more visible others less but all have that issue now. :-1:

**Comment by Mottie** [comment]
Ok, try v2.11.23... sorry, crying babies cause distractions & halt OCD checking mode 😉.

**Comment by the-j0k3r** [comment]
mmm I was adding a couple of fixes so  you better rebase :)

**Comment by the-j0k3r** [comment]
lol what a mess, so we still doing the normal style too?

I fixed a comma in user css post 2.11.23  normal style was ok 

ontopic issue gone. looks wonderful now, like a babys diaper 
.
.
.
.
before using.

**Comment by Mottie** [comment]
Yeah, I've only been updating the normal style to keep things consistent... this repo still has a build script. It's not *that* easy to remove the normal style. We'll need to:

* Update the gruntfile; or, completely remove it and rewrite the patch, minor & major scripts in bash.
* Remove unneeded devDependencies.
* Remove unneeded build tools.
* Rewrite the usercss build tool to update the themes, if we should ever add another... or maybe we could just manually do it since it's so rare? Although, I wouldn't want to ever manually do it for GitHub-Dark again.
* Update docs.
