### ISSUE TITLE
Jobs messages stay white

### ISSUE THREAD

**Issue by flyx** [StylishThemes/StackOverflow-Dark#119]
There are quite some issues when viewing jobs messages. I will provide screenshots of the actual page and the inspector separately to edit out sensitive information and show issues on different elements. First, the message list ( https://stackoverflow.com/jobs/messages#!/inbox ):

![screen shot 2018-08-21 at 10 38 18](https://user-images.githubusercontent.com/791710/44391405-083c8f80-a530-11e8-8821-9e13c6f9dc7f.png)

First of all, the text color of the *Select All* checkbox is off:

<img width="1706" alt="screen shot 2018-08-21 at 10 52 10" src="https://user-images.githubusercontent.com/791710/44391510-5c477400-a530-11e8-843c-08a9b6f10953.png">

Then, obviously, the whole message list is white:

<img width="1705" alt="screen shot 2018-08-21 at 10 54 24" src="https://user-images.githubusercontent.com/791710/44391644-b3e5df80-a530-11e8-93ff-b7cdc395eedf.png">

Problems continue when viewing a specific message:

![screen shot 2018-08-21 at 10 38 44](https://user-images.githubusercontent.com/791710/44391708-e1328d80-a530-11e8-8316-0684819588ba.png)

The top buttons are not correctly styled:

<img width="1705" alt="screen shot 2018-08-21 at 10 57 35" src="https://user-images.githubusercontent.com/791710/44391812-18a13a00-a531-11e8-9509-ef598e9c1f70.png">

The message area is white:

<img width="1705" alt="screen shot 2018-08-21 at 10 58 54" src="https://user-images.githubusercontent.com/791710/44391875-39698f80-a531-11e8-9a1c-78d73ebe1198.png">

As is the answer area:

<img width="1704" alt="screen shot 2018-08-21 at 11 00 15" src="https://user-images.githubusercontent.com/791710/44391986-703fa580-a531-11e8-8d76-8eae1d53cc69.png">

**Comment by Mottie** [comment]
Hi @flyx!

I only have a few messages, so I'm not sure if I've covered every message tab. Also please let me know if the message buttons (mark as read/unread) are styled properly as I my inbox is empty.

I've updated the css/usercss files without bumping the version. You may have to copy/paste the style or reinstall it.

**Comment by the-j0k3r** [comment]
@Mottie Greetings and salutations

:+1: for the msg fix, I cant dupe my inbox is also empty but I did fix the navigation border in https://github.com/StylishThemes/StackOverflow-Dark/commit/630ca7c396a06ba21fff2caa8277457e62f87751

**Comment by flyx** [comment]
This fixed every problem I reported. I checked all tabs I have content in (I don't have applications or questions) and there's still a small piece of white here (lower area of message):

<img width="1699" alt="screen shot 2018-08-21 at 14 44 52" src="https://user-images.githubusercontent.com/791710/44402142-1d75e600-a551-11e8-907d-b8dc6e4de519.png">

**Comment by the-j0k3r** [comment]
@flyx pushed new usercss release out, I recommend you switch to the usercss if you arent using it already, StylishThemes is moving away from USO and normal CSS styles.

let me know if all issues are fixed.

**Comment by flyx** [comment]
@the-j0k3r updated, that rectangle is still as white as before. From what I can tell, inspector look identical to before.

**Comment by the-j0k3r** [comment]
@flyx would you mind checking if https://github.com/StylishThemes/StackOverflow-Dark/commit/b97646ccf0d197be382047e4db3831d40eea80c9 fixes it? if not check if `.msg-form .msg-controls` in same position does it.

Thank you

**Comment by flyx** [comment]
@the-j0k3r the commit did not fix it, `.msg-form .msg-controls` did. Sorry for taking my time.

The `Send Message` button is blue-ish unlike the others; I am unsure whether it's correctly themed. HTML in my previous pic.

**Comment by the-j0k3r** [comment]
> The Send Message button is blue-ish unlike the others; I am unsure whether it's correctly themed. HTML in my previous pic.

If you disable the theme you should get a sense if the styling is right for the button.
If you feel that is wrong, feel free to open another issue.

> @the-j0k3r the commit did not fix it, .msg-form .msg-controls did. Sorry for taking my time.

No problem, :) it should be fixed in 7d2b5af for next release.
