### ISSUE TITLE
New contributor label

### ISSUE THREAD

**Issue by Humberd** [StylishThemes/StackOverflow-Dark#121]
The new contributor under user level needs restyling. Take a look here https://raspberrypi.stackexchange.com/questions/88493/wlan0-interface-disappears-after-overclocking-sd-card

![image](https://user-images.githubusercontent.com/10242142/44623409-edba3b80-a8cc-11e8-9781-172f412efe75.png)

**Comment by Mottie** [comment]
Hi @Humberd!

Thanks for letting us know!

Note: The usercss has been updated, we're no longer updating the style on userstyles.org. The usercss file won't work as you'd expect in Stylish, so use Stylus or xStyle to update.
