### ISSUE TITLE
Some components on "Ask a qustion" route are unstyled

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/StackOverflow-Dark#125]
Sorry for deleting the boilerplate for issue reporting, but this is not that big issue.

If you navigate to https://stackoverflow.com/questions/ask, the
- How to ask
- Similar questions
- How to tag
- Tags choises

have become unstyled.

Start writing a question and populate all fields to reproduce the issue.

**Comment by Mottie** [comment]
Hi @VladimirDev93!

The Stackoverflow-Dark style available on userstyles.org is no longer being updated. If you install Stackoverflow-dark usercss [from this repo](https://github.com/StylishThemes/StackOverflow-Dark#installation), you'll see all of these issues have been fixed.

**Comment by Mottie** [comment]
I do see that the added tags are not styled, so I'll get that fixed here shortly.

**Comment by VladimirDev93** [comment]
Oh, I didn't know that. Thank you.
