### ISSUE TITLE
Reputation gain of accepted answer on user reputation tab is unreadable

### ISSUE THREAD

**Issue by ikkentim** [StylishThemes/StackOverflow-Dark#126]
https://stackoverflow.com/users/(id)/(name)?tab=reputation

````html
<span class="rep-up bounty-indicator-tab accept-indicator-tab">+25</span>
````

![image](https://user-images.githubusercontent.com/2820647/45811197-bcb30800-bccc-11e8-8299-040cd02bc8cc.png)

**Comment by Mottie** [comment]
It sounds like you're using the version on userstyles.org... we've stopped updating the style on their site. If you would like the most up-to-date version, please install this UserCSS style directly from our GitHub repository (if you're using Stylus): https://github.com/StylishThemes/StackOverflow-Dark#installation

**Comment by ikkentim** [comment]
I installed the UserCSS style as instructed but this still seems to be broken

![image](https://user-images.githubusercontent.com/2820647/45884983-87ceb000-bdb5-11e8-8338-a044bf8011d0.png)

![image](https://user-images.githubusercontent.com/2820647/45885040-a634ab80-bdb5-11e8-838b-6663b7297101.png)

**Comment by Mottie** [comment]
Odd, it looks fine to me

![](https://user-images.githubusercontent.com/136959/45885530-4e2d8300-bd7c-11e8-9205-f887a88842d6.png)

**Comment by ikkentim** [comment]
It happens only on accepted answers, are those accepted answers?

Im running Chrome Version 69.0.3497.100  by the way

**Comment by ikkentim** [comment]
Ah, on the summary page it is only the reputation list, not the answers list:

![image](https://user-images.githubusercontent.com/2820647/45886021-41c71b80-bdb8-11e8-9eef-9c3e883a2bc3.png)

**Comment by Mottie** [comment]
Ok, I don't have any entries like that, would you please share the HTML of that row so I know what class is being added:

```html
<tr>
  <td class="rep-amount count-cell"><span class="rep-up">+10</span></td>
  <td><a href="..." class="answer-hyperlink ">...</a></td>
</tr>
```

**Comment by ikkentim** [comment]
Reputation list on user profile summary tab
``` html
            <tr>
                <td class="rep-amount count-cell"><span class="rep-up special-rep">+25</span></td>
                <td><a href="..." class="answer-hyperlink ">...</a></td>
            </tr>
```

Reputation gain list on user profile reputation tab
``` html
        <tr class="rep-breakdown-row rep-recent-row expandable-row">
            <td class="rep-left">
                    <span class="rep-up bounty-indicator-tab accept-indicator-tab">+25</span>
                                    </td>
            <td class="rep-time" title="2018-09-21 14:43:32Z">
                14:43
            </td>

                <td class="rep-desc">2 events</td>
                <td class="rep-link async-load load-prepped" data-load-url="...">...</td>
        </tr>
```

**Comment by Mottie** [comment]
Sorry for taking so long to fix this... please test the latest version.

**Comment by ikkentim** [comment]
On the summary tab it is fixed, but on the reputation tab the issue's still there

**Comment by ikkentim** [comment]
Now it's fixed, awesome! 👍
