### ISSUE TITLE
Next badge progress bar (when silver) is not very readable

### ISSUE THREAD

**Issue by ikkentim** [StylishThemes/StackOverflow-Dark#128]
https://stackoverflow.com/users/(id)/(name)

![image](https://user-images.githubusercontent.com/2820647/45811720-21bb2d80-bcce-11e8-838f-5b131bc13f54.png)

````html
<div id="badge-card-next" class="s-progress s-progress__badge s-progress__silver js-badge-select-popup js-gps-track" data-gps-track="profile_next_badge.click({ view_type: 1 })">
                            <div class="grid gs12 gsx m0 s-progress--label">
                                <div class="grid--cell mr0 s-badge--image badge2"></div>
                                <div class="grid grid__center fl1 s-badge--label">Civic Duty</div>
                            </div>
                            <div class="s-progress--bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="51" style="width: 51%;"></div>
                        </div>
````

**Comment by Mottie** [comment]
It sounds like you're using the version on userstyles.org... we've stopped updating the style on their site. If you would like the most up-to-date version, please install this UserCSS style directly from our GitHub repository (if you're using Stylus): https://github.com/StylishThemes/StackOverflow-Dark#installation
