### ISSUE TITLE
Contributors Guidelines Missing

### ISSUE THREAD

**Issue by spottedmahn** [StylishThemes/StackOverflow-Dark#133]
`CONTRIBUTING.md` seems to be missing.

In the [`readme.md`](https://github.com/StylishThemes/StackOverflow-Dark/blob/master/README.md) there is a reference to: https://github.com/StylishThemes/StackOverflow-Dark/blob/master/CONTRIBUTING.md which yields a `404`.

**Comment by Mottie** [comment]
Hi @spottedmahn!

Thanks, [we have one](https://github.com/StylishThemes/StackOverflow-Dark/blob/master/.github/CONTRIBUTING.md) it's just the link that's broken.

**Comment by spottedmahn** [comment]
I figured you did!

I'll submit a PR to fix the readme, thanks for the quick response!

**Comment by Mottie** [comment]
Already done 😸

**Comment by spottedmahn** [comment]
oh, nice!  Thanks 😊
