### ISSUE TITLE
gaming.stackexchange.com

### ISSUE THREAD

**Issue by Podesta** [StylishThemes/StackOverflow-Dark#139]
Is there an underlying reason for not supporting gaming.stackexchange.com, or was it simply a decision made in the past due to lack of time to properly support/test it? I mean, would there be any issues if someone wanted to make a PR to support it?

**Comment by Mottie** [comment]
Hi @Podesta!

When originally adding support for most StackExchange sites, the gaming site was significantly different enough from the others that it was skipped. Adding support would be nice if you'd like to help out.
