### ISSUE TITLE
StackOverflow: 1) vote buttons aren't styled, 2) code line-height issue

### ISSUE THREAD

**Issue by tophf** [StylishThemes/StackOverflow-Dark#141]
* **Browser**: Chrome 70
* **Operating System**: Windows 7
* **Screenshot**:

![image](https://user-images.githubusercontent.com/1310400/50541091-3d787e80-0baf-11e9-8bb8-8c932590df96.png)

* **HTML of the section where the issue occurs**:

```html
<div class="votecell post-layout--left">
  <div class="js-voting-container grid fd-column ai-stretch gs4 fc-black-200" data-post-id="53972086">
    <button class="js-vote-up-btn grid--cell s-btn s-btn__unset c-pointer" title="This answer is useful"
            aria-pressed="false" aria-label="up vote" data-selected-classes="fc-theme-primary">
      <svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="36" height="36" viewBox="0 0 36 36">
        <path d="M2 26h32L18 10z"></path>
      </svg>
    </button>
    <div class="js-vote-count grid--cell fc-black-500 fs-title grid fd-column ai-center c-pointer"
         itemprop="upvoteCount" data-value="0" title="View upvote and downvote totals" tabindex="0">0
    </div>
    <button class="js-vote-down-btn grid--cell s-btn s-btn__unset c-pointer" title="This answer is not useful"
            aria-pressed="false" aria-label="down vote" data-selected-classes="fc-theme-primary">
      <svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="36" height="36" viewBox="0 0 36 36">
        <path d="M2 10h32L18 26z"></path>
      </svg>
    </button>
    <div class="js-accepted-answer-indicator grid--item fc-green-500 ta-center p4 d-none"
         title="loading when this answer was accepted..." aria-label="accepted">
      <svg aria-hidden="true" class="svg-icon iconCheckmarkLg" width="36" height="36" viewBox="0 0 36 36">
        <path d="M6 14l8 8L30 6v8L14 30l-8-8z"></path>
      </svg>
    </div>
  </div>
</div>
```

---

1. Vote buttons aren't styled, hence overly prominent
2. As for the scrollbar, the problem is that it's shown more often for code that's close to the maximum overflow height on SO (`max-height: 600px;`). For example, if someone tries not to exceed it when posting there, your style defeats the effort by setting `line-height: 1.4` on `pre.prettyprint` overriding the default 1.3 and it makes the carefully crafted code boxes overflow. NBD, of course (as I've already tweaked it in my local microstyle), but why change the line height anyway? It's not like 1.4 is sooo much better than the the default and not that the default is bad either. Maybe you can remove that rule or add an option.

**Comment by Mottie** [comment]
Hi @tophf!

Good points! We never altered the syntax highlighting themes, but yes they would look better without the `line-height` set. I'll take care of it.
