### ISSUE TITLE
Pink "toast" is unreadable

### ISSUE THREAD

**Issue by tophf** [StylishThemes/StackOverflow-Dark#142]
* **Browser**: Chrome 70
* **Operating System**: Windows 7
* **Screenshot**:

![image](https://user-images.githubusercontent.com/1310400/50681699-7c7a5a00-101d-11e9-95cc-ce7b3b5704df.png)

* **HTML of the section where the issue occurs**:

````html
<body>
  <div class="s-toast js-toast js-stacks-managed-popup js-fades-with-aria-hidden" aria-hidden="false" style="top: 60px;">
    <aside class="s-notice s-notice__danger">
      <div class="grid gs16 gsx ai-center jc-space-between">
        <div class="grid--cell"><p class="m0 js-toast-body" id="js-notice-toast-message" role="status" tabindex="0">You
          last voted on this answer 11 mins ago. Your vote is now locked in unless this answer is edited.</p></div>
        <div class="grid--cell mr0 js-notice-actions">
          <div class="grid">
            <button class="p8 s-btn grid grid__center fc-dark" tabindex="0" role="button" aria-label="Dismiss">
              <svg aria-hidden="true" class="svg-icon iconClearSm m0" width="14" height="14" viewBox="0 0 14 14">
                <path
                    d="M12 3.41L10.59 2 7 5.59 3.41 2 2 3.41 5.59 7 2 10.59 3.41 12 7 8.41 10.59 12 12 10.59 8.41 7z"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </aside>
  </div>
</body>
````

The toast appears if you try to vote on a post you already voted on more than five minutes ago. 
The div is a direct child of `<body>`.

**Comment by the-j0k3r** [comment]
Also blue just pressing the arrow up on that page

https://meta.stackoverflow.com/questions/378440/caveat-emptor-making-students-aware-they-cannot-delete-their-homework-questions?cb=1

```html
<p class="m0 js-toast-body" id="js-notice-toast-message" role="status" tabindex="0">Thanks for the feedback! Votes cast by those with less than 15 <a href="/help/whats-reputation">reputation</a> are recorded, but do not change the publicly displayed post score.</p>
```

![checks](https://user-images.githubusercontent.com/31389848/50688609-776dd880-1026-11e9-90b6-286f6a097052.PNG)

Ill assume that there are other affected toasts,

**Comment by the-j0k3r** [comment]
I found some more in user profile, sadly IDK what I did to see it in first place, so no CSS caught. This is more of a reminder for me to look at it again. =)
