### ISSUE TITLE
Insert Link

### ISSUE THREAD

**Issue by spottedmahn** [StylishThemes/StackOverflow-Dark#144]
* **Browser**: Chrome 71
* **Operating System**: Win10
* **Screenshot**:

![image](https://user-images.githubusercontent.com/14079228/50726239-582f8380-10d8-11e9-995b-eaf286089a67.png)

* **HTML of the section where the issue occurs**:

````html
<div class="wmd-inline-dialog js-wmd-inline-dialog--47564076" style="display: block;">
  <p><b>Insert Hyperlink</b></p>
  <div class="grid"><input class="s-input">
    <button class="s-btn s-btn__outlined ws-nowrap ml16 js-insert-link-button">Add link</button> 
    <button class="s-btn js-cancel-button">Cancel</button>
  </div>
</div>
````

**Comment by Mottie** [comment]
Hi @spottedmahn!

Thanks for reporting this issue.

**Comment by spottedmahn** [comment]
Looks great!  Thanks @Mottie 

![image](https://user-images.githubusercontent.com/14079228/50726644-ebb78300-10dd-11e9-9e66-fc3e30e5bbc8.png)
