### ISSUE TITLE
Star icon not respect the fact post marked as favorite

### ISSUE THREAD

**Issue by e-g1gor** [StylishThemes/StackOverflow-Dark#146]
* **Browser**: Firefox for OpenSUSE 64.0 (64-bit)
* **Operating System**: OpenSUSE Tumbleweed
* **Screenshot**:
![screenshot_20190110_200156](https://user-images.githubusercontent.com/29484330/50985626-d5faf100-1515-11e9-9b2a-3a6f11f33ddb.png)

Current style sheet force "favorite" icon to be gray whether it marked or not.
The rule that responsible is in .iconStar selector. Removing this selector from style sheet make things look as below:
![screenshot_20190110_202602](https://user-images.githubusercontent.com/29484330/50985703-093d8000-1516-11e9-9c93-bad77b6e7609.png)
Im not sure if it will corrupt appearance in any other place. Maybe this rule even obsolete. Take a look pls, thx.

**Comment by the-j0k3r** [comment]
Thank you for your report, this should be fixed momentarily.
