### ISSUE TITLE
Input text box placeholder color is nearly the same as text color

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/StackOverflow-Dark#149]
* **Browser**:

    Google Chrome version 74.0.3702.0 dev (64-Bit)

* **Operating System**:

    Windows 10 64-bit German

* **Screenshot with placeholder**:

    ![image](https://user-images.githubusercontent.com/415439/52739869-1d234880-2fd2-11e9-959b-57f1899f41ce.png)

* **Screenshot with regular text**:

    ![image](https://user-images.githubusercontent.com/415439/52740155-b5213200-2fd2-11e9-93d2-8e6222303b9e.png)

* **HTML of the section where the issue occurs**:

    ````html
    <input name="q" type="text" placeholder="Search…" value="" autocomplete="off" 
           maxlength="240" class="s-input js-search-field ">
    ````
The input text boxes (e.g. the search box as described above) do have placeholder colors that are the same as regular input text.

This makes it hard to see whether a field is already filled out or just has a placeholder being shown.

**Suggestion**

Please make the input placeholder color darker as the normal input text color.

**Comment by Mottie** [comment]
Hi @UweKeim!

Hmm, it seems that our definition for `input:-webkit-autofill` is causing the placeholder to have brighter text. The definition is set to `#fff` to fix issue #123. The `:placeholder` color is set to `#ddd`.

Changing the `input:-webkit-autofill` to a darker color will alter both the placeholder and input text. This might be a browser bug. I'll need to investigate when I get some time.

CC: @silverwind @the-j0k3r

**Comment by the-j0k3r** [comment]
> Hmm, it seems that our definition for `input:-webkit-autofill` is causing the placeholder to have brighter text.

Unrelated afaics, autofill only targets the autofill fields the regular placeholder was actually set too bright for ages added in https://github.com/StylishThemes/StackOverflow-Dark/commit/85ec3c0af3c6e6797d792c1601705aa52c234586 by you @Mottie  =)

Fixed anywho and pushed some other fixes and made a small release, @UweKeim please update ;) and have a nice day/night ppl.

**Comment by UweKeim** [comment]
Thanks a lot, @the-j0k3r. I'm already clicking like mad on the "update" button in the Stylus Chrome extension settings.

But it always tells me that all Styles are up-to-date.

![image](https://user-images.githubusercontent.com/415439/52768593-38bc3c80-302e-11e9-9f46-17bf18c74968.png)

I'm new to this Stylus thing; am I doing it wrong somehow?

**Comment by UweKeim** [comment]
And just as I hit submit on my comment, an update _was_ available.

Unfortunately the placeholder is still bright white.

**Comment by UweKeim** [comment]
From looking at [your changes](https://github.com/StylishThemes/StackOverflow-Dark/commit/80a05875a38a4f41dbb446f75cce057e86fdd5b6), it seems you are _removing_ the darker colors and _adding_ ligher colors for the placeholder.

Shouldn't it be the other way around?

**Comment by the-j0k3r** [comment]
`#dddddd` is brighter than `#999999`

**Comment by the-j0k3r** [comment]
here is a before and after, gif starts with `#ddd` and switches to `#999` after.

![placeholder](https://user-images.githubusercontent.com/31389848/52769213-ef6cec80-302f-11e9-8070-980a312958a7.gif)

Typing text is `#fff` which is considerably brighter than `#999`,

I could darken it further to `#888` or `#777` but I thought that was a bit too dark

**Comment by UweKeim** [comment]
Sorry, honestly, that I don't get it and am stealing your valuable time 😢. 

I've done now:

- Checked for updates again
- Disabled ad blocker and the like
- Disabled other extensions like Tampermonkey
- Restarted my browser

Still the placeholder is `#FFFFFF` and the normal text is `#FFFFFF` as well.

Any chance for me to debug this on my own?

**Comment by the-j0k3r** [comment]
I have switched to chrome to test, seems you are right.

The culprit is 

```css
  .actual-edit-overlay, input, input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0 1000px #111 inset;
    -webkit-text-fill-color: #fff !important;
  }
```

The actual selector overriding my changes is `input`

https://github.com/StylishThemes/StackOverflow-Dark/blob/master/stackoverflow-dark.user.css#L238-L241

Give me a minute Ill see what is going on.

**Comment by the-j0k3r** [comment]
Try again in a a few seconds, I pushed a fix that actually fixes it =) Tested in Chrome, Vivaldi and Firefox

**Comment by UweKeim** [comment]
Thanks a lot, now it works and is actually distinguishable!

Very fast and helpful support, I'm honestly impressed.

**Comment by the-j0k3r** [comment]
Thank you for your kind words. Your very welcome. Have a nice day ;)

**Comment by UweKeim** [comment]
Any donation link like PayPal or something like that available?

**Comment by the-j0k3r** [comment]
I cant see anything like that available. The only related chat I found is https://github.com/StylishThemes/GitHub-Dark/issues/318#issuecomment-222331700 and below that.

=)

**Comment by UweKeim** [comment]
OK, thanks, just donated to [msf.org](https://www.msf.org).
