### ISSUE TITLE
Chessboards not chequered

### ISSUE THREAD

**Issue by jtojnar** [StylishThemes/StackOverflow-Dark#155]
The style forces transparent background on table cells, breaking the chequered pattern chess boards are supposed to have.

* **Browser**: Firefox 66
* **Operating System**: Linux
* **Link to page with the issue**: https://chess.stackexchange.com/questions/24166/what-professional-game-has-the-quickest-sequence-starting-from-move-one-to-qua/24177#24177
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/705123/56456495-93934c80-636d-11e9-831d-fc8415c8da78.png)

**Comment by Mottie** [comment]
Hi @jtojnar!

Thanks for reporting this issue. I'll get it fixed shortly.
