### ISSUE TITLE
Not working on pages with bright background-image

### ISSUE THREAD

**Issue by haxj** [StylishThemes/StackOverflow-Dark#158]
On pages with a background image (askubuntu, unix/crypto.stackexchange, ....), dark themes not showing correctly.
For example, on crypto.stackexchange.com:
![image](https://user-images.githubusercontent.com/22296968/59560973-5f25cf00-9044-11e9-8164-223b96c960e9.png)

**Comment by the-j0k3r** [comment]
Can you please post a direct link to one or more of the pages where issue is present?

**Comment by the-j0k3r** [comment]
Hi again @haxj and thank you for reporting this issue.

I cant see any issue at all in `crypto.stackexchange.com`

![Screenshot_2019-06-16 Cryptography Stack Exchange](https://user-images.githubusercontent.com/31389848/59561818-d5b2d480-9024-11e9-8d70-9002958954bc.png)

**Comment by haxj** [comment]
Hi @the-j0k3r, thanks for your quick response!
Actually, it's my mistake when I installed the theme. Sorry about that. :)

**Comment by the-j0k3r** [comment]
No problem, glad its working now.
