### ISSUE TITLE
Answer in Black color

### ISSUE THREAD

**Issue by SmartManoj** [StylishThemes/StackOverflow-Dark#160]
Answer is black also when hovering
`a.s-link__grayscale, .s-link.s-link__grayscaleddds`
* **Browser**: Chrome
* **Operating System**: Win
* **Link to page with the issue**: https://stackoverflow.com/questions/ask
* **Screenshot**:
![image](https://user-images.githubusercontent.com/7231077/59859171-e56e4800-9399-11e9-8a27-58a9300f4c1d.png)

**Comment by Mottie** [comment]
Hi @SmartManoj!

I'll have this fixed momentarily.
