### ISSUE TITLE
Clicking elements of expanded dropdown menu at left-top in StackOverflow Teams

### ISSUE THREAD

**Issue by OrigamiDream** [StylishThemes/StackOverflow-Dark#161]
* **Browser**: Chrome (latest)
* **Operating System**: macOS 10.14
* **Link to page with the issue**: https://stackoverflow.com/teams
* **Screenshot**:
![image](https://user-images.githubusercontent.com/5837620/60066643-bdd50200-9742-11e9-9b7d-bda4baf53ba8.png)
The 'X' button is white.

This looks the cause.
![image](https://user-images.githubusercontent.com/5837620/60066689-e3620b80-9742-11e9-902c-280aa3525d39.png)

Thanks.

**Comment by the-j0k3r** [comment]
@OrigamiDream, Thank you for reporting this issue to us.

Should now be fixed in v3.2.17, [click here](https://github.com/StylishThemes/StackOverflow-Dark/raw/master/stackoverflow-dark.user.css) to update your style via stylus or check for updates for styles in your addon.
