### ISSUE TITLE
Visited links in stackoverflow.com/questions don't show in visited links color

### ISSUE THREAD

**Issue by GertArnold** [StylishThemes/StackOverflow-Dark#169]
In the last update v3.3.17 and at least one earlier, visited links in stackoverflow.com/questions don't display in my configured "Visited links color", 145,151,157 (RGB). Other pages do (f.e. https://stackoverflow.com/users/861716/gert-arnold?tab=activity).

Browser: Chrome latest version
OS: Windows 10

Top 3 links are visited:

![image](https://user-images.githubusercontent.com/5769086/61172960-8660b500-a58c-11e9-9650-46d68c5e3c1e.png)

Still enjoying this great theme!

**Comment by Mottie** [comment]
Thanks @GertArnold!

It's been updated.
