### ISSUE TITLE
How do I ask a good question? hard to read

### ISSUE THREAD

**Issue by spottedmahn** [StylishThemes/StackOverflow-Dark#179]
>How do I ask a good question?

Is hard to read in this awesome theme 😊

* **Browser**: Chrome 76
* **Operating System**: Win 10
* **Link to page with the issue**: 
* **Screenshot**:

![image](https://user-images.githubusercontent.com/14079228/63205041-93316680-c06c-11e9-978f-a683e60ba7bb.png)

![image](https://user-images.githubusercontent.com/14079228/63205058-d25fb780-c06c-11e9-9d79-5ecfefafe6dc.png)

**Comment by the-j0k3r** [comment]
Hi @spottedmahn, thax for opening this issue with us.

Could you please provide a link to that page Im finding hard to find that exact page, also could you elaborate on whats hard to read about it?

**Comment by spottedmahn** [comment]
Hi @the-j0k3r  👋

>Could you please provide a link to that page I'm finding hard to find that exact page

https://stackoverflow.com/questions/ask

paste in "Xamarin App Not Returning from B2C Login"

>also could you elaborate on what's hard to read about it?

My bad, I should have highlighted that.  Here it is:

![image](https://user-images.githubusercontent.com/14079228/64272505-8090ab80-cf0d-11e9-9ae5-5d681c8628f4.png)

**Comment by the-j0k3r** [comment]
Ah I see the problematic portion of text now after see: and others.

Should be fixed in a bit.

**Comment by spottedmahn** [comment]
>Thanks for the reply though I had gotten to it just after asking :/

😂, np it happens 👍

Thanks for all your work on this nice style!

**Comment by the-j0k3r** [comment]
> Thanks for all your work on this nice style!

Youre welcome, its fastly approaching max insanity, Im considering a re-write.
