### ISSUE TITLE
Dark titles in Email Settings and Community Digests

### ISSUE THREAD

**Issue by athlonusm** [StylishThemes/StackOverflow-Dark#183]
The setting titles in Email Settings and Community Digests are already dark and barely visible against the default background. I'm using the latest version of Vivaldi.

Here are some screenshots, taken on English Language Learners.

Email Settings, the style is on:
![ELL_Email_Dark](https://user-images.githubusercontent.com/32931827/65815309-3211bc80-e1ee-11e9-9866-2ce065547c55.PNG)

Email Settings, the style is off:
![ELL_Email_Light](https://user-images.githubusercontent.com/32931827/65815316-45248c80-e1ee-11e9-8cb2-f1cddd3ee096.PNG)

Community Digests, the style is on:
![ELL_CD_Dark](https://user-images.githubusercontent.com/32931827/65815326-5bcae380-e1ee-11e9-99f6-62504edfa102.PNG)

Community Digests, the style is off:
![ELL_CD_Light](https://user-images.githubusercontent.com/32931827/65815328-64231e80-e1ee-11e9-9abf-db5339196b5d.PNG)

**Comment by the-j0k3r** [comment]
I dont have anything in the community digests to be able to reproduce But I was able to fix the Email settings screenshot.

Would you be able to inspect the element and pass me a screenshot + HTML so I can see about fixing that?

**Comment by athlonusm** [comment]
Your first fix fixed everything. Thanks!

**Comment by the-j0k3r** [comment]
Thanks for feedback.
