### ISSUE TITLE
Accepted questions lose Code Colouring

### ISSUE THREAD

**Issue by LarnuUK** [StylishThemes/StackOverflow-Dark#187]
When viewing a question/answer that has an **accepted** solution for the active user the colouring in code all disappears. For example, notice that this accepted answer is all in white:
![image](https://user-images.githubusercontent.com/20837086/68229784-c5a98a80-ffef-11e9-87bc-ad61e395e0e5.png)

It also causes the top bar to malfunction, and you can't access the menus (they all become links). Questions where a different answer has been accepted don't have this flaw:
![image](https://user-images.githubusercontent.com/20837086/68229658-909d3800-ffef-11e9-842f-5e1091ddbbd3.png)

* **Firefox 70**: 
* **Windows 10 1903 & Ubuntu 19.04**: 
* **https://stackoverflow.com/questions/58674426/loop-through-different-tables-for-count/58674918#58674918**:

**Comment by LarnuUK** [comment]
Thanks @the-j0k3r . I can't say I understand such things (SQL Server is my forté), however, seems more odd that as a result the top bar doesn't work.

Normal behaviour:
![Links working with Style](https://user-images.githubusercontent.com/20837086/68244402-ad943400-000c-11ea-8f95-0f4b92024d2b.gif)

Behaviour on a page with accepted answer (using backspace to return to previous page):
![Links not working with Style](https://user-images.githubusercontent.com/20837086/68244454-c1d83100-000c-11ea-8aaa-d83c71b4a07e.gif)

**Comment by Mottie** [comment]
Hi @LarnuUK!

First off, please make sure you're using the most up-to-date style. If you've installed the style from userstyles.org, uninstall it, we don't support that site anymore. Install it using [Stylus](https://add0n.com/stylus.html) and [the link from our readme](https://github.com/StylishThemes/StackOverflow-Dark#installation).

As for the problems you're encountering... This style shouldn't be blocking the dropdown menu. It adds css styling, and I can't think of a case where it would prevent a dropdown menu from opening.

As for the syntax highlighting, maybe try a different theme:

<img width="691" alt="" src="https://user-images.githubusercontent.com/136959/68259734-48d2dc80-0000-11ea-8a2a-74692a05919b.png">

**Comment by the-j0k3r** [comment]
I cant duplicate the dropdown menu issues either, but I can duplicate the CSS syntax issues, probably because of the inline html animated style.

I dont think that can be fixed either. @Mottie what do you think?

**Comment by LarnuUK** [comment]
> First off, please make sure you're using the most up-to-date style. If you've installed the style from userstyles.org, uninstall it, we don't support that site anymore. Install it using [Stylus](https://add0n.com/stylus.html) and [the link from our readme](https://github.com/StylishThemes/StackOverflow-Dark#installation).

Thanks @Mottie . I click the link to double check, and can confirm I have the latest version installed.
 
> As for the problems you're encountering... This style shouldn't be blocking the dropdown menu. It adds css styling, and I can't think of a case where it would prevent a dropdown menu from opening.

This surprises me, as i've replicated this problem on 2 very different machines. The animated gifs (showing the menus not loading) is from a Ubuntu 19.04 Machine. I'm now on Windows 10 1903 and the same problem occurs:
![FPD3yDfnTe](https://user-images.githubusercontent.com/20837086/68284336-347cf700-0075-11ea-84fd-988f4bec1d6e.gif)

If I disable the theme, however, the menus work fine; so having it activated is certainly the cause:
![VyniO33OFF](https://user-images.githubusercontent.com/20837086/68284356-4363a980-0075-11ea-823d-419f8dcc839a.gif)

> As for the syntax highlighting, maybe try a different theme:
> 
> <img alt="" width="691" src="https://user-images.githubusercontent.com/136959/68259734-48d2dc80-0000-11ea-8a2a-74692a05919b.png">

Changing the theme has no effect:
![vuh86Cledw](https://user-images.githubusercontent.com/20837086/68284585-af461200-0075-11ea-855d-8b79cb2ad9e7.gif)

**Comment by the-j0k3r** [comment]
Try with fresh browser profiles (backup old first) for the menu lockup issues.

**Comment by LarnuUK** [comment]
Worth noting, as well, that it isn't just my answer that losing colouring; it is **all** syntax highlighting on the page:
![image](https://user-images.githubusercontent.com/20837086/68284863-2085c500-0076-11ea-976f-8e66197ed3a9.png)

**Comment by the-j0k3r** [comment]
Read up regarding syntax color loss. its the animated inline style loading on background that breaks this.

**Comment by LarnuUK** [comment]
> 
> 
> Try with fresh browser profiles (backup old first) for the menu lockup issues.

That wiould infer that the profiles are corrupt on 2 complete different PCs, in different locations (Office vs Home), with different operating systems, would it not? That seems very unlikely.

**Comment by the-j0k3r** [comment]
>Yes, saw this, but your gif only demonstrated that against an accepted answer. i was clarifying it affects all answers (and the question) not just my own answer.

This is what I know about the syntax color loss: 

If you dont link to an accepted answer directly this issue wont happen, its just because your link https://stackoverflow.com/questions/58674426/loop-through-different-tables-for-count/58674918#58674918 is direct to accepted answer thus triggers inline animation, thus breaks.

If you click https://stackoverflow.com/questions/58674426/loop-through-different-tables-for-count instead the syntax color remains because the animation isnt triggered directly.

>That wiould infer that the profiles are corrupt on 2 complete different PCs, in different locations (Office vs Home), with different operating systems, would it not? That seems very unlikely.

Its a insurance policy against eventualities (idk if you sync profiles but its has been known to happen), simply that.
Another insurance policy is you disabling all your other addons except stylus,

**Comment by LarnuUK** [comment]
> Its a insurance policy against eventualities (idk if you sync profiles but doesn't matter its has been known to happen), simply that.
> Another insurance policy is you disabling all your other addons except stylus,

I do sync profiles, but not work and home ones; so the profiles at Home and Office and different. I'll give shredding the profile a go at home, as doing so at work will impact workload. May not get a chance to do that this evening.

Alternatively, I could spin up a new login at home, install stylus (and only stylus) on Firefox and see if i can replicate the issue (might be easier if you're happy with that).

**Comment by the-j0k3r** [comment]
> Alternatively, I could spin up a new login at home, install stylus (and only stylus) on Firefox and see if i can replicate the issue (might be easier if you're happy with that).

Im happy no matter what, I would be happier if you found the root of the issue. Its not this style, that we all can assure you CSS cant do any of that.

**Comment by the-j0k3r** [comment]
OK found a way to address the syntax color loss [when linking directly to an accepted answer](https://stackoverflow.com/questions/58674426/loop-through-different-tables-for-count/58674918#58674918). in https://github.com/StylishThemes/StackOverflow-Dark/commit/3c8ad8a1bcdfcaa3b64a74ee10e9bda373e8637c

![generic](https://user-images.githubusercontent.com/31389848/68293463-4b7c1300-008e-11ea-9de0-ffe6f3509a48.gif)

It autocloses the issue.

Please update your style to version v3.3.42.

Regarding other issue, feel free to use this ticket to discuss further, but its not caused by the StackOverflow Dark style and cant be fixed here.

Thanks for understanding.

**Comment by LarnuUK** [comment]
> Regarding other issue, feel free to use this ticket to discuss further, but its not caused by the StackOverflow Dark style and cant be fixed here.

You say that, but update the style has fixed **both** issues. :)

**Comment by the-j0k3r** [comment]
> You say that, but updating the style has fixed **both** issues. :)

Im happy for you. That will be $50 =)
