### ISSUE TITLE
Request - Background Image: none

### ISSUE THREAD

**Issue by Merrit** [StylishThemes/StackOverflow-Dark#188]
Add the option under Background Image to choose 'None', the same way it is available in the Wikipedia theme:

![image](https://user-images.githubusercontent.com/9575627/70543257-1c970800-1b38-11ea-8038-fbace7342a4d.png)

I personally find the default dots distracting and unpleasant, and the simple grey the 'None' option gives looks excellent to me.

**Comment by the-j0k3r** [comment]
You can at this time while waiting for this feature, try to set custom without anything in field below

**Comment by Merrit** [comment]
The StackOverflow theme doesn't actually have the dropdown the Wikipedia version does, just a box for the image url. If I try to leave it blank it throws an error:

![image](https://user-images.githubusercontent.com/9575627/70550420-b7491400-1b43-11ea-912f-8fca69299c2d.png)

**Comment by the-j0k3r** [comment]
try `url("")`

**Comment by Merrit** [comment]
Yep, that looks to work. Awesome.

Thanks much. Love this theme <3

**Comment by the-j0k3r** [comment]
OK I added this in https://github.com/StylishThemes/StackOverflow-Dark/commit/566c1cab094c351cedadfbd12e47575f451dc649

Features are a breaking change so everyone will have to reconfigure these areas to their liking,

**Comment by Merrit** [comment]
Beautiful!

I tried it out and it looks gorgeous, nice and user-friendly way to do it too.

Thank you so much :)

**Comment by the-j0k3r** [comment]
Youre welcome.

We do it like that in our GitHub Dark style so it was mostly copy and paste =)
