### ISSUE TITLE
Allow disabling dimming images

### ISSUE THREAD

**Issue by teohhanhui** [StylishThemes/StackOverflow-Dark#189]
**Describe the change you'd like**

I'd like to see the images without reduced brightness or opacity. That's not what I expect from a dark theme (though some might like that).

**Additional context**

Basically, allow customizing / disabling these: https://github.com/StylishThemes/StackOverflow-Dark/blob/7619dee2e44c64964f816bd2661393f6bf2eff7c/stackoverflow-dark.user.css#L1109-L1114

**Comment by teohhanhui** [comment]
In the meantime, this can be overridden locally by a [companion style](https://github.com/openstyles/stylus/wiki/Writing-styles#making-a-companion-style):

https://gist.github.com/teohhanhui/f276cdb09afb5a6fb643fa1a7f77fb98

**Comment by the-j0k3r** [comment]
basically just use update to 4.0.1 and use this pre-existing setting

![Capture](https://user-images.githubusercontent.com/31389848/71417744-450a2080-2667-11ea-96a1-1bb811de0b5c.PNG)

**Comment by teohhanhui** [comment]
Thank you!
