### ISSUE TITLE
Site header of some stack exchange subs looks particularly bad

### ISSUE THREAD

**Issue by h1nk** [StylishThemes/StackOverflow-Dark#191]
While then entire point of this user style is to give Stack Exchange sites a dark theme, it does clash quite a lot with some of the imagery in some subs, such as the music one for example. Maybe a lighter grey color could be used instead of such a dark/near-black one for the site header.

* **Browser**: Firefox
* **Operating System**: Linux
* **Link to page with the issue**: https://music.stackexchange.com/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/12993584/72220642-a6c4f880-354a-11ea-9fba-e2ab345e6f29.png)

**Comment by the-j0k3r** [comment]
This style supports many sites and subdomains like this, its impossible to style them all in one go many (more than ones that are styled) are unstyled like this one, which is using the default img colors

There's two ways around this

```
@-moz-document domain("music.stackexchange.com") {
  .site-header {
	  background-color: #ffd972 !important;
  }
}
```

else the alternative is 

```
@-moz-document domain("music.stackexchange.com") {
  .site-header .wmx100 {
    filter: invert(1) hue-rotate(180deg);
  }
  .site-header {
	  background-color: #222 !important;
  }
  .site-header .site-header--container {
    background: none;
  }
}
```

tell me which you prefer and Ill add it.

Thanks for report in any case.

**Comment by h1nk** [comment]
@the-j0k3r the first option seems best for this particular domain.

**Comment by the-j0k3r** [comment]
Please force upgrade to latest version by [clicking here](https://github.com/StylishThemes/StackOverflow-Dark/raw/master/stackoverflow-dark.user.css)

Also fixed a few other subdomains headers/footers etc.
