### ISSUE TITLE
Issue with review stats page 

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#192]
As shown by the screenshot, this style makes the review status page unreadable.

I don't know how to solve it right now, but I'll be glad to help! ;D

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://stackoverflow.com/review/triage/stats
* **Screenshot**: ![image](https://user-images.githubusercontent.com/14969290/72864125-cb8b3f80-3cb1-11ea-9961-a3586d6d244c.png)

**Comment by the-j0k3r** [comment]
I also fixed other issues around those pages left unreported. Please upgrade to 4.0.6
