### ISSUE TITLE
Problem displaying markdown hints when asking a new question

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#193]
This style hides the code markdown hint when asking a new question.

As shown by the screenshots, it doesn't completely hides, but the helper text is impossible to read.

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://stackoverflow.com/questions/ask
* **Screenshots**: 
![image](https://user-images.githubusercontent.com/14969290/72942733-fbd6ea80-3d52-11ea-8315-481452ae12c0.png)
![image](https://user-images.githubusercontent.com/14969290/72942763-0ee9ba80-3d53-11ea-92e2-5f8eb9544695.png)

**Comment by the-j0k3r** [comment]
The style technically doesn't hide this, it is simply not handled.

I see other issues around this page also, may as well fix while here. please upgrade to 4.0.8

Thx for report.
