### ISSUE TITLE
Loss of color for upvote/downvote arrows

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/StackOverflow-Dark#195]
The upvote/downvote buttons have an additional class `.fc-theme-primary` to show a different color when a button is active. The dark theme currently squashes this and doesn't show the active colors.

This occurs on any StackExchange site, and also affects the favorite question button.

* **Browser**:  Firefox Nightly (latest)
* **Operating System**:  Debian Testing x64
* **Link to page with the issue**:  Any question/answer that you vote on (while logged in)
* **Screenshot**: From https://stackoverflow.com/q/33040703/

**With Style Enabled**
![image](https://user-images.githubusercontent.com/7613032/73144904-11754880-40a2-11ea-881d-cb85f3abbedb.png)

**With Style Disabled**
![image](https://user-images.githubusercontent.com/7613032/73144929-3d90c980-40a2-11ea-92c2-a26b488a7100.png)

**Comment by the-j0k3r** [comment]
Actually by default this doesnt work for me at all on hover. Only when clicking which is also wrong as there is no longer an hover state.

See

![generic](https://user-images.githubusercontent.com/31389848/73158276-a51b3900-40e3-11ea-8b4c-cb26bb441e42.gif)

Only when clicking, I can try adding that.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/StackOverflow-Dark/commit/393a50b8f2394815032bbdaab7ea743d0e68412e was what works to make it work like default.

any other solutions also welcome
