### ISSUE TITLE
CodeReview broken

### ISSUE THREAD

**Issue by cipri-tom** [StylishThemes/StackOverflow-Dark#20]
Hi,

Hat down to your amazing effort, sir! Your contribution is relieving a lot of pain in my eyes. 
I was able to mod some things for myself, but the size of the overall style is too much for my limited CSS knowledge. Thank you for taking your time to provide all these fixes and mods.

As per the recommendation in the style, I am posting about a broken site: http://codereview.stackexchange.com
They add "background-color" to a lot of elements :cry: . I don't understand why they can't be consistent. So the home page and the question page are broken :(

**Comment by Mottie** [comment]
Hi @cipri-tom!

Thanks for reporting this! An update is now available on userstyles.org.

**Comment by cipri-tom** [comment]
Thank you!
And you've also fixed askubuntu. Amazing! gittip ? :grinning:

**Comment by Mottie** [comment]
LOL thanks... If you are so inclined, here is a link: https://gratipay.com/~Mottie/
