### ISSUE TITLE
Weird behavior of related/linked question vote count on Server Fault

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#200]
There's something strange heppening on the related or linked questions vote count on Server Fault. 

The vote count is larger for some reason, just wanted to point out ;D

* **Browser**: Chrome
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://serverfault.com/questions/252921/how-to-remove-empty-blank-lines-from-a-file-in-unix-including-spaces
* **Screenshots**: 
![image](https://user-images.githubusercontent.com/14969290/73494610-99ee3480-4393-11ea-926b-98ab391654f6.png)
![image](https://user-images.githubusercontent.com/14969290/73494647-aa9eaa80-4393-11ea-836c-81a1d2fbf528.png)

**Comment by the-j0k3r** [comment]
I'll check it out, thx for report. =)

**Comment by the-j0k3r** [comment]
The issue was some CSS that was added over 2 years ago. Fix incoming.
