### ISSUE TITLE
Visual issue on editting watched tags

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#201]
It seems that SO uses images as their symbol to edit watched tags. Because of that and together with SO-Dark, the delete watch tag renders almost like a white ball, making it a little uncanny.

The hover effect is nice though! ;D

* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: https://stackoverflow.com/
* **Screenshots**:
![image](https://user-images.githubusercontent.com/14969290/73508324-53f89700-43ba-11ea-9fd5-88c10b48fefc.png)
![image](https://user-images.githubusercontent.com/14969290/73508347-61ae1c80-43ba-11ea-91c5-8d2e6161da27.png)

**Comment by the-j0k3r** [comment]
The problem is SO has two tag delete icons styles, these ones really stray a great deal from the others so I added something as close as I can.

![generic](https://user-images.githubusercontent.com/31389848/73527535-82569080-4413-11ea-8224-94f061ce38e4.gif)
