### ISSUE TITLE
Alert on previous flags are not following the style

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#202]
I believe that this case hasn't been covered before because it's rare to find this message.

But since it's not following the SO-Dark style I think it's a bug.

I've tested only on StackOverflow.

* **Browser**:  Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: Any post page on question's flag modal
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/14969290/73844675-cbd22180-47ff-11ea-957e-1043fe57b364.png)

![image](https://user-images.githubusercontent.com/14969290/73844650-bbba4200-47ff-11ea-8e79-501c9780e71e.png)

**Comment by the-j0k3r** [comment]
@bernardoduarte Thanks for this report

Please inspect the element and copy the outer HTML OR a copy of the corresponding CSS rules.
The CSS rules would be better

Else, Trying to fix this is by guessing is impossible.

**Comment by bernardoduarte** [comment]
```html
<div class="flag-quality-warning">
    <span>Attention: some of your recent flags have been declined - please <a href="/users/flag-summary/7395911?showDeclined=true">review</a> them before flagging this post!</span>
</div>
```

**Comment by the-j0k3r** [comment]
Thats totally unhelpful, try getting the rules please.

**Comment by the-j0k3r** [comment]
I managed to fix the text color on the explanations but cant find a way to duplicate this.

**Comment by the-j0k3r** [comment]
ping

**Comment by bernardoduarte** [comment]
Sorry for not answering before, somehow Github didn't give me a notification. Anyway, now I'm no longer receiving this message, a few hours later after posting here I got an accepted flag and now they are no longer displaying it for me ;/

As soon as I get a rejected flag I'll post here all the css that I can retrieve ;D

**Comment by bernardoduarte** [comment]
I've got an idea, and I think it worked. I've copy and pasted the HTML posted by me here on the page and here is what I've got:
![image](https://user-images.githubusercontent.com/14969290/74054717-4ac08900-49bd-11ea-8ff8-150f1e8fdf56.png)
Anything else you need, just ask ;D

**Comment by the-j0k3r** [comment]
Thats great, Ill add that soon as tomorrow =) thanks.
