### ISSUE TITLE
Accepted question check always green.

### ISSUE THREAD

**Issue by rdornas** [StylishThemes/StackOverflow-Dark#203]
I just made a question in StackOverflow and I accepted one of the answers. However, to me, the one who proposed the question, both checks are shown in green, what made me confuse. Here are the following screenshots of the problems. In both cases, the element I inspected is the bottom check mark, as it is the one exhibiting problem:

• Original mode with only accepted answer in green
<img width="1476" alt="Captura de tela 2020-02-06 19 01 16" src="https://user-images.githubusercontent.com/25906665/73982480-142e3400-4913-11ea-99d2-d91a35b21f93.png">

• Dark mode with both checks in green
<img width="1475" alt="Captura de tela 2020-02-06 19 00 05" src="https://user-images.githubusercontent.com/25906665/73982484-185a5180-4913-11ea-93f6-1ae7dfefc5a0.png">

Unfortunately, as this is shown only to the user who made the question, I am afraid I can't share personal details for you to test it.

**Comment by the-j0k3r** [comment]
@rdornas Thank you for this bug report, Hopefully the changes I did will help. Let me know if it doesn't,

**Comment by the-j0k3r** [comment]
@rdornas Would you please share the selectors for the upvote in showing in blue on your SO Dark screenshot?

TIA =)

**Comment by rdornas** [comment]
> @rdornas Would you please share the selectors for the upvote in showing in blue on your SO Dark screenshot?
> 
> TIA =)

Ok, but those upvotes in blue are not a bug, I really upvoted both answers.

<img width="1468" alt="Captura de tela 2020-02-07 12 20 34" src="https://user-images.githubusercontent.com/25906665/74041359-43d94c80-49a4-11ea-950e-d8af5f408a3d.png">

**Comment by the-j0k3r** [comment]
They arent a bug they shouldn't be blue is all.

I cant see any selectors to pick on that, can you copy and paste the actual NOT svg path rules surrounding that pls?

**Comment by rdornas** [comment]
Yes, they change the color. The behaviour is ok, no issue!

And yes, the main issue is fixed! Thank you!!!
