### ISSUE TITLE
Smudge on profile badges on SE sites

### ISSUE THREAD

**Issue by bernardoduarte** [StylishThemes/StackOverflow-Dark#207]
I haven't checked all sites, but it seems that most of them display this behavior of leaving a smudge around the badge. That happens for all badges, bronze, silver and gold.

As a suggestion, I believe that could be the style that happens once we hover the badge, on SE it creates a black background, but since this style is a dark one it could use the badge's color.

Sorry for creating to many issues, just want to help ;D

* **Browser**: Firefox
* **Operating System**: Ubuntu
* **Link to page with the issue**: https://stackoverflow.com/users/22656/jon-skeet
* **Screenshots**:
With style:
![image](https://user-images.githubusercontent.com/14969290/74362575-b2087f80-4da7-11ea-9c2a-c41c2cee674a.png)
Without style:
![image](https://user-images.githubusercontent.com/14969290/74362599-bcc31480-4da7-11ea-8b71-79fb085d9acc.png)

**Comment by the-j0k3r** [comment]
I wouldnt call this a `smudge` but a background. Fixed anywho for now.
