### ISSUE TITLE
Background of questions are no longer dark

### ISSUE THREAD

**Issue by TwentyFourMinutes** [StylishThemes/StackOverflow-Dark#209]
As you can see in the image attached below, the background of the Asking Question page is not dark.

![image](https://user-images.githubusercontent.com/36015290/75586154-fc5e5180-5a73-11ea-9325-894bb13260fa.png)

I guess it is the `div.container` element, if you remove the `background-color` attribute it works again.

* **Browser**:  Brave
* **Operating System**: Windows 10
* **Link to page with the issue**: https://stackoverflow.com/questions/ask
* **Screenshot**:
![image](https://user-images.githubusercontent.com/36015290/75585972-9bcf1480-5a73-11ea-992d-f19e59de03c9.png)

**Comment by the-j0k3r** [comment]
Lots of updates going on in SO, so its hardly a bug, rather expected.
