### ISSUE TITLE
Next Page Overlay Issue

### ISSUE THREAD

**Issue by spottedmahn** [StylishThemes/StackOverflow-Dark#210]
* **Browser**: Chrome 80
* **Operating System**: Win10
* **Link to page with the issue**: [Seeking useful Eclipse Java code templates [closed] ](https://stackoverflow.com/questions/1028858/seeking-useful-eclipse-java-code-templates?answertab=votes#tab-top)
* **Screenshot**:
![image](https://user-images.githubusercontent.com/14079228/75599748-b4d8c500-5a75-11ea-9bed-d869f00d2b90.png)

![image](https://user-images.githubusercontent.com/14079228/75599749-b904e280-5a75-11ea-9f8f-1d293034b673.png)

**Comment by the-j0k3r** [comment]
We just cant have nice things

**Comment by spottedmahn** [comment]
thanks for the super quick fix ⚡!!

Looks good 👍

![image](https://user-images.githubusercontent.com/14079228/75686546-70624a80-5c6a-11ea-80a2-d7650f2156c2.png)

**Comment by the-j0k3r** [comment]
IDK about looks good, its the worst place to put paging elements, but Im not going to redesign that.
