### ISSUE TITLE
Reputation `rep-breakdown` class background missing

### ISSUE THREAD

**Issue by lennybacon** [StylishThemes/StackOverflow-Dark#212]
* **Browser**: Firefox Developer  (latest) 
* **Operating System**: Windows 10 (latest)
* **Link to page with the issue**: https://stackoverflow.com/users/12679/daniel-fisher-lennybacon?tab=reputation
* **Screenshot**:
![image](https://user-images.githubusercontent.com/272164/77450854-2ba67b00-6df4-11ea-822c-62bb5db56e3b.png)

Fix:

![image](https://user-images.githubusercontent.com/272164/77451063-73c59d80-6df4-11ea-868d-fc1921511faf.png)

**Comment by the-j0k3r** [comment]
@lennybacon thanks for reporting.

Here I see unstyled issue at https://stackoverflow.com/users/12679/daniel-fisher-lennybacon?tab=reputation&sort=post and the solution doesn't seem to be colored red.

Ill have a look in the morning and fix this though. Its tied up to https://github.com/StylishThemes/StackOverflow-Dark/issues/180 and newer changes break previous fixes.

**Comment by lennybacon** [comment]
@the-j0k3r The red was just to show that the class affects the unstyled region of course :-)

No need to hurry. I patched my css and If there won't be new releases soon they will not be overwritten.

**Comment by the-j0k3r** [comment]
Ive fixed the issue and other issues unreported at https://stackoverflow.com/users/story/12679 and other pages.

Release in a few. You will need to force update the style since your local changes trump auto-updates.

**Comment by the-j0k3r** [comment]
Please upgrade to 4.4.2 [click here](https://github.com/StylishThemes/StackOverflow-Dark/raw/master/stackoverflow-dark.user.css)

Also keep your eyes peeled, I fully expect more breakages to be incoming, currently the main site is undergoing active changes, Ive noticed every other month things break as updates are pushed from their side.

**Comment by lennybacon** [comment]
![image](https://user-images.githubusercontent.com/272164/77525433-5098fd80-6e89-11ea-9984-133d612db420.png)

**Comment by the-j0k3r** [comment]
fixed in 4.4.3 should have ran tests before pushing ;)

**Comment by lennybacon** [comment]
:-)

**Comment by the-j0k3r** [comment]
try 4.4.4 even, omg I need another coffee =)

**Comment by lennybacon** [comment]
Worked. Thanks!
