### ISSUE TITLE
How to switch between themes?

### ISSUE THREAD

**Issue by Hesamedin** [StylishThemes/StackOverflow-Dark#213]
Yesterday, I received a notification in the top of the webpage that said I can try the dark mode.
I accepted and the theme of the StackOverflow turned into the dark theme.
After having it for a few hours, I decided to turn it back into its classic theme but I wasn't able to find it.

From where I can switch between themes?

Thank you.

**Comment by xt0rted** [comment]
Their dark theme is unrelated to this project, but you can switch your settings by going to https://stackoverflow.com/users/preferences/current.
