### ISSUE TITLE
Unreadable logic keywords (or, and, ...) in custom filters

### ISSUE THREAD

**Issue by imsodin** [StylishThemes/StackOverflow-Dark#216]
* **Browser**: Firefox 67.0.1
* **Operating System**: debian testing
* **Link to page with the issue**: https://security.stackexchange.com/questions?edited=true
* **Screenshot**:
While typing "or" it's correctly displayed white (readable), but as soon as you hit space/start typing the next tag, the text turns black on a black backgroud:

![image](https://user-images.githubusercontent.com/15955093/83325372-19b9dc00-a26c-11ea-9121-4a4d0fcb58e3.png)
![image](https://user-images.githubusercontent.com/15955093/83325385-26d6cb00-a26c-11ea-83bb-b8f55a90ac95.png)

Outer html from debugger on the parent span containing the tags and "or":
```
<span><span class="s-tag rendered-element">encryption<a class="js-delete-tag s-tag--dismiss" title="Remove tag"><svg class="svg-icon iconClearSm pe-none" width="14" height="14" viewBox="0 0 14 14"><path d="M12 3.41L10.59 2 7 5.59 3.41 2 2 3.41 5.59 7 2 10.59 3.41 12 7 8.41 10.59 12 12 10.59 8.41 7z"></path></svg></a></span><span class="rendered-element">or</span><span class="s-tag rendered-element">hash<a class="js-delete-tag s-tag--dismiss" title="Remove tag"><svg class="svg-icon iconClearSm pe-none" width="14" height="14" viewBox="0 0 14 14"><path d="M12 3.41L10.59 2 7 5.59 3.41 2 2 3.41 5.59 7 2 10.59 3.41 12 7 8.41 10.59 12 12 10.59 8.41 7z"></path></svg></a></span></span>
```

**Comment by the-j0k3r** [comment]
Thanks for reporting this, fix in 3,2,1...

**Comment by the-j0k3r** [comment]
Please update to 4.4.5
