### ISSUE TITLE
Syntax theme no longer work

### ISSUE THREAD

**Issue by Fubuchi** [StylishThemes/StackOverflow-Dark#218]
* **Theme version**: 4.4.7 
* **Browser**:  Firefox Developer, Opera 70 and Chrome 85
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: https://stackoverflow.com/questions/53716171/spring-boot-parsing-requestbody/53717883#53717883
* **Screenshot**: No matter what syntax theme I chosen, it always the same:

![image](https://user-images.githubusercontent.com/42483897/94224383-5d6fda00-ff1c-11ea-8f81-a8657d796c38.png)

**Comment by the-j0k3r** [comment]
Just acknowledging the report, I need to investigate and see what exactly is going on, just real life so no time to look at it at the moment..

**Comment by the-j0k3r** [comment]
OK Ive done something simple with a couple of preset themes and a custom, Will be removing the built into style because the new design is incompatible with the existing.

**Comment by the-j0k3r** [comment]
Consult the readme for instructions.

Any further themes need to be added in same format, the design works, however SO defines which selectors apply, not the theme, any included selectors are to fix some issues with their design and to be compatible with how SO is currently done.
