### ISSUE TITLE
Newsletter sign-up widget has duplicate header

### ISSUE THREAD

**Issue by LWChris** [StylishThemes/StackOverflow-Dark#219]
* **Browser**: Vivaldi 3.3.2022.47 Stable, 32-bit (Chromium Engine, like Chrome 85.0.4183.123)
* **Operating System**: Windows 10 64-bit
* **Link to page with the issue**:  
* **Screenshot**:

![image](https://user-images.githubusercontent.com/845152/97019448-a08b9000-1550-11eb-96f6-f02228f856e7.png) ![image](https://user-images.githubusercontent.com/845152/97019408-923d7400-1550-11eb-8f98-d627b1f48dd3.png)

```
<div id="newsletter-ad" class="s-sidebarwidget mb16">
    <div class="s-sidebarwidget--header">
        <svg aria-hidden="true" class="svg-icon iconMail" width="18" height="18" viewBox="0 0 18 18"><path d="M1 6l8 5 8-5V4L9 9 1 4c0-1.1.9-2 2-2h12a2 2 0 012 2v10a2 2 0 01-2 2H3a2 2 0 01-2-2V6z"></path></svg> Love this site?
    </div>
    <div class="s-sidebarwidget--content d-block">

        <p id="newsletter-ad-header">Get the <b>weekly newsletter!</b> In it, you'll get:</p>
        <ul>
            <li>The week's top questions and answers</li>
            <li>Important community announcements</li>
            <li>Questions that need answers</li>
        </ul>
    <div id="newsletter-signup-container" class="ta-center">
        <button id="newsletter-signup" class="s-btn s-btn__filled">Sign up for the digest</button>
    </div>
    <p id="newsletter-preview-container" class="mt8 mb0 ta-center">see an <a href="/digest/preview" id="newsletter-preview">example newsletter</a></p>

    </div>
</div>
```

Source of duplicate seems to be:
```
#newsletter-ad::before {
    content: "Love this site?";
    font-size: 18px !important;
}
```

Source of padding seems to be:
```
.answer, #newsletter-ad {
    padding: 10px !important;
}
```

**Comment by the-j0k3r** [comment]
Is this a style bug or present when not using this style?

**Comment by LWChris** [comment]
It's a style bug.

When _StackOverflow-Dark_ is disabled:

![image](https://user-images.githubusercontent.com/845152/97019448-a08b9000-1550-11eb-96f6-f02228f856e7.png)

When the style is enabled in its current form:

![image](https://user-images.githubusercontent.com/845152/97019408-923d7400-1550-11eb-8f98-d627b1f48dd3.png)

With the style enabled, but modified as suggested in PR #220:

![image](https://user-images.githubusercontent.com/845152/97021597-52c45700-1553-11eb-9ad0-8ca89afd1588.png)
