### ISSUE TITLE
line spacing for prettyprinted code

### ISSUE THREAD

**Issue by boneskull** [StylishThemes/StackOverflow-Dark#22]
Hi,

Great work on this theme!  I noticed the line height is a bit tight on the prettyprinted code:

![screenshot before](http://content.screencast.com/users/chiller/folders/Jing/media/1d95be87-b899-4829-b9bc-5f199b3ed98f/00000316.png)

Here it is after increasing it to `1.4em`:

![screenshot after](http://content.screencast.com/users/chiller/folders/Jing/media/053d9ef0-a766-4d22-b878-ee2df04a7e07/00000317.png)

Let me know what you think.

**Comment by Mottie** [comment]
Hi @boneskull!

Hmm, only some of the [themes](https://github.com/StylishThemes/StackOverflow-Dark/tree/master/themes/src) have a defined line-height, and when they do it is set to `1.5` (no units). I guess to be consistent, I can make sure they are all set to `1.4em`, no problem :grin:
