### ISSUE TITLE
White code blocks on Stackexchange

### ISSUE THREAD

**Issue by d-Rickyy-b** [StylishThemes/StackOverflow-Dark#223]
Thanks for creating this awesome style!

Code blocks (`<pre><code>...</code></pre>`) are displayed as white on Stackexchange.

* **Browser**: Mozilla Firefox 82.0.2 (64-Bit)
* **Operating System**: Windows 10 (Build 19041.572)
* **Link to page with the issue**: https://unix.stackexchange.com/questions/423164/nginx-emerg-ssl-certificate-directive-is-duplicate-add-new-ssl-enabled-s
* **Screenshot**:

![grafik](https://user-images.githubusercontent.com/5798157/98571025-604c4180-22b4-11eb-9cdd-981541d6c9d7.png)

The same code blocks on Stackoverflow work just fine: https://stackoverflow.com/questions/22656219/how-do-i-set-the-license-for-images-on-my-site-in-google-images

**Comment by the-j0k3r** [comment]
Please see notes on readme and install the https://github.com/StylishThemes/StackOverflow-Dark#additional-styles
