### ISSUE TITLE
Code blocks unreadable

### ISSUE THREAD

**Issue by CodePurble** [StylishThemes/StackOverflow-Dark#224]
* **Browser**: Brave Browser Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)
* **Operating System**: Arch Linux
* **Link to page with the issue**: https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences#4842438
* **Screenshot**:
![image](https://user-images.githubusercontent.com/49452779/99383031-57cabb00-28f3-11eb-9b3e-e2fe5e2e138e.png)

All code blocks are unreadable because the font colour of the text closely matches the background colour.

**Comment by CodePurble** [comment]
Interestingly, adding the [syntax theme user-css](https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/stackoverflow-syntax-themes.user.css) seems to have fixed it.

**Comment by the-j0k3r** [comment]
> Interestingly, adding the [syntax theme user-css](https://raw.githubusercontent.com/StylishThemes/Feature-Override-Styles/master/stackoverflow-syntax-themes.user.css) seems to have fixed it.

There is no other solution.

**Comment by CodePurble** [comment]
Sorry about that. I think the disclaimer in the README be a little bit before where it is. I'll open up a PR then, and thank you!
