### ISSUE TITLE
Code blocks are now white

### ISSUE THREAD

**Issue by RomanKornev** [StylishThemes/StackOverflow-Dark#228]
Today, all code blocks became white. Looks like a new design update.

* **Browser**: Chromium 80
* **Operating System**: Windows 10 x64
* **Link to page with the issue**:  https://unix.stackexchange.com/questions/260735/how-to-use-sudo-u-option/260739
* **Screenshot**:
![image](https://user-images.githubusercontent.com/5807561/102214328-27257380-3ee9-11eb-8b3c-9275e61b0fdc.png)

**Comment by the-j0k3r** [comment]
Please read the readme and or the pinned issue instead.
