### ISSUE TITLE
tex stackexchange forum

### ISSUE THREAD

**Issue by GamerGurke15** [StylishThemes/StackOverflow-Dark#23]
![screenshot](https://cloud.githubusercontent.com/assets/10208785/12295566/2262b630-ba02-11e5-9dba-90062754ed33.jpg)
[tex.stackexchange.com](http://tex.stackexchange.com/ ) is not displayed properly. Is this indented, as this site is not supported or do you just overlooked it? I wasn't able to quick-fix it for now, even though I will continue trying.

**Comment by Mottie** [comment]
Hi @GamerGurke15!

It looks fine to me. From looking at the Stylish icon in the screenshot, there are 2 styles applied to that site, maybe the second one is interfering?

**Comment by GamerGurke15** [comment]
hmh no I have deactivated the one (it was [Darker Google](https://userstyles.org/styles/43463/darker-google)) and it is still the same :/

**Comment by Mottie** [comment]
What browser are you using?

**Comment by GamerGurke15** [comment]
oh I got it working, by redownloading the theme, no idea what was the problem but it is working now ^^

**Comment by Mottie** [comment]
To me, it looks like the background color is set to white, or the background image is white.

Oh, ok! I'm glad it's all good now!

**Comment by GamerGurke15** [comment]
no the bg color was properly set, i don't know, i changed something to the scroll bar, probably I interfered there with something else.
