### ISSUE TITLE
unreadable text and missed implementation

### ISSUE THREAD

**Issue by wadawada** [StylishThemes/StackOverflow-Dark#230]
* **Browser**: Chrome
* **Operating System**: Windwos 10
* **Link to page with the issue**:
* https://meta.stackoverflow.com/questions/386150/should-stack-overflow-revisit-the-dark-mode-question-in-light-of-new-situations/386152#386152
*  https://superuser.com/a/1642241/1086679
* **Screenshot**:
* 
![bbb](https://user-images.githubusercontent.com/9424144/118358862-a4572200-b535-11eb-954e-fd0609860edf.png)
![bbb2](https://user-images.githubusercontent.com/9424144/118358874-ade08a00-b535-11eb-8af2-fa83ff62a0bb.png)

**Comment by the-j0k3r** [comment]
Please read https://github.com/StylishThemes/StackOverflow-Dark#additional-styles install  StackOverflow Syntax Themes usercss

Thanks.
