### ISSUE TITLE
The background is bright everywhere

### ISSUE THREAD

**Issue by OmarNamis** [StylishThemes/StackOverflow-Dark#236]
* **Browser**: Firefox & Chrome.
* **Operating System**: Windows 10.
* **Link to page with the issue**: All pages, including homepage.
* **Screenshot**:
![image](https://user-images.githubusercontent.com/14346945/126893494-1cd5d02e-c75e-4171-9015-5156694f37d2.png)

**Comment by the-j0k3r** [comment]
Yep, whoever decided on the new CSS var selectors upstream, it use to be so simple and sane, But clearly supporting Internet explorer is more important.
