### ISSUE TITLE
Add CSS "color-scheme: dark;"

### ISSUE THREAD

**Issue by perz1val-git** [StylishThemes/StackOverflow-Dark#237]
There is [this](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) css property, which will make chromium use default dark scrollbars.

**Comment by the-j0k3r** [comment]
Thanks you for that request

Scrollbars styling is not included in this style and will never be.

You can instead use https://github.com/StylishThemes/Overlay-Scrollbars

this is documented at https://github.com/StylishThemes/StackOverflow-Dark#additional-styles

Thx.
