### ISSUE TITLE
entry turns grey (original color) on onmouseover

### ISSUE THREAD

**Issue by henningsway** [StylishThemes/StackOverflow-Dark#30]
I like the style. But when I move over an entry, it actually turns grey again and this hurts my eyes? Is this a bug, a feature or a problem with my setup? :)

**Comment by Mottie** [comment]
Hi @henningsway!

What entry specifically?

**Comment by henningsway** [comment]
the whole entry I guess, like the whole post by a person. The code stays dark, but the background of the text turns light grey (which is the original stackoverflow color I believe).

Ah, I just checked. It happens for the examples in Documentation (Beta) only, which I have been using a lot lately, I guess. :)

**Comment by Mottie** [comment]
Please be even more specific...

Here is a documentation entry I made for [javascript classes](http://stackoverflow.com/documentation/javascript/503/document-object-model-dom/10738/classes#t=201608011024517637431), what about it is too dark?

I do think the editing icons across the top are too dark, I can brighten those up a bit.

![docs](https://cloud.githubusercontent.com/assets/136959/17291434/7af4e29c-57a9-11e6-85dd-9c61128bc4f0.gif)

**Comment by henningsway** [comment]
this is what it looks for me.

![anim](https://cloud.githubusercontent.com/assets/1403304/17292167/5f2d3d7c-57e8-11e6-9466-7f0bad70dcde.gif)

**Comment by Mottie** [comment]
I have a feeling you need to [update your style from userstyles](http://userstyles.org/styles/35345).

**Comment by henningsway** [comment]
hmm, that didn't solve it. Maybe I have to check my other extensions then. Thank you for looking into it.

**Comment by Mottie** [comment]
Any update on this?

**Comment by henningsway** [comment]
somehow the problem is gone for me. awesome!

**Comment by Mottie** [comment]
Great! Thanks for the update!
