### ISSUE TITLE
Parens in code blocks are invisible

### ISSUE THREAD

**Issue by rpatterson** [StylishThemes/StackOverflow-Dark#35]
Parens in code blocks are nearly invisible:

http://stackoverflow.com/a/530571/624787

**Comment by Mottie** [comment]
Hi @rpatterson!

What syntax theme are you using?

**Comment by rpatterson** [comment]
Sorry for not including a screenshot!  Here it is:

![image](https://cloud.githubusercontent.com/assets/222721/18811318/e9bf72fa-8260-11e6-85ff-fa15ed906001.png)

As for syntax theme, I'm not sure what that is.  I poked around my stackoverflow.com settings and couldn't find anything.  I also tried disabling all other syntax related extensions and disabling all other user styles and got the same result.

**Comment by Mottie** [comment]
Are you installing the style from here: https://userstyles.org/styles/35345/stackoverflow-dark?

The syntax theme is the top-most selection

![2016-09-24 16_30_40-stackoverflow dark - themes and skins for stackoverflow - userstyles org](https://cloud.githubusercontent.com/assets/136959/18811424/569270fe-8274-11e6-8c9e-f10470e6973a.png)

**Comment by rpatterson** [comment]
I did clicked the "Update with Stylish" button on that page and now parens are clear and bright.  Sorry!

**Comment by rpatterson** [comment]
Err, sorry and thanks.  :-)

**Comment by Mottie** [comment]
LOL no worries
