### ISSUE TITLE
Mobile browser - some parts stay white

### ISSUE THREAD

**Issue by Bluscream** [StylishThemes/StackOverflow-Dark#36]
![tmp_3313-screenshot_20161202-005336-1585652466](https://cloud.githubusercontent.com/assets/3318223/20817772/e5dd1e68-b829-11e6-87b8-e7a102b964e9.png)
![tmp_3313-screenshot_20161202-005347-1515133241](https://cloud.githubusercontent.com/assets/3318223/20817776/e9cbe068-b829-11e6-9b5e-d31039f37f67.png)
Test url: http://stackoverflow.com/questions/40472231/qt-button-take-as-much-space-as-the-text-on-it-needs/40474243#40474243

**Comment by Mottie** [comment]
Hi @Bluscream!

I'm not seeing the white styling. Please make sure to update the style directly from [userstyles](https://userstyles.org/styles/35345/stackoverflow-dark).

**Comment by Bluscream** [comment]
![tmp_3313-screenshot_20161202-010016844816029](https://cloud.githubusercontent.com/assets/3318223/20817898/bce97dde-b82a-11e6-9f69-cd3e233fa04b.jpg)

**Comment by Mottie** [comment]
Maybe the classes are different for a mobile device? Please share the class names that you see.

**Comment by Bluscream** [comment]
How can i debug them without having a computer available? With only the android tablet

**Comment by Mottie** [comment]
LOL that would be my question as well.

**Comment by ywyak** [comment]
found one image background isn't white in
https://stackoverflow.com/users/account-recovery

proof:
http://i.imgur.com/pghb0YJ.png

**Comment by Mottie** [comment]
@ywyak Fixed.

**Comment by Zeeex** [comment]
Broken on this link: http://stackexchange.com/newsletters/newsletter?site=stackoverflow.com
![image](https://cloud.githubusercontent.com/assets/16362320/21748564/37ead9fe-d588-11e6-9dcc-7ecbb9143f49.png)

**Comment by Mottie** [comment]
Thanks @Zeeex!

They did a lot of inline styling on this page, and included a lot of `!important` flags; so if the style looks a little off, it is because we can't override those particular inline styles.

**Comment by Destroyer** [comment]
you can just debug it in chrome - Developer tools(F12)->Toggle device toolbar(icon next to Elements)
switch to e.g. iphone 6s plus and refresh the page
so the problem with navigation bar is: 

    .nav {background-color: #333}

**Comment by the-j0k3r** [comment]
mm, wouldnt you guys be able to use addons like https://addons.mozilla.org/en-GB/firefox/addon/user-agent-switcher-revived/?src=userprofile and fake a mobile device to get classes?

**Comment by Mottie** [comment]
Actually, in Chrome you can use "Toggle device toolbar (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd>)" to emulate a mobile device now... 

![](https://user-images.githubusercontent.com/136959/31284634-bfd7bcbc-aa7e-11e7-85e6-68901a27ad92.png)

It looks like the page is styled now. It'd be nice to get confirmation with an actual mobile device though.

**Comment by the-j0k3r** [comment]
added some fixes for two reported issues on this issue https://github.com/StylishThemes/StackOverflow-Dark/commit/f18308bdb8c8c9c1f946f3bcffed241167f6b317 Im closing this for now.
