### ISSUE TITLE
Highlighted jobs stay white/off-white

### ISSUE THREAD

**Issue by rjkerrison** [StylishThemes/StackOverflow-Dark#38]
As shown below, highlighted search results at [StackOverflow Jobs](stackoverflow.com/jobs) have a light background which clashes with the dark aesthetic and the light text.

![so-jobs-mishighlight](https://cloud.githubusercontent.com/assets/7150842/21569308/a3c94bf0-ceb3-11e6-8753-4f364e4bfb7f.png)

I've fixed this locally using the styling below.

    .-item._highlighted {
      background: #111111!important;
    }

**Comment by Mottie** [comment]
Hi @rjkerrison!

Thanks for letting us know! It is now all styled and available on userstyles.
