### ISSUE TITLE
Current unstyled things

### ISSUE THREAD

**Issue by LWChris** [StylishThemes/StackOverflow-Dark#39]
- [ ] "Insert a link" popup (white, unreadable)
- [ ] Meta StackExchange header shows alt text
- [ ] Winter Bash hats popup (not so important as I guess it'll disappear in 2 days)
- [ ] Activity impact card separator line (I feel it should be gray)

**Comment by Mottie** [comment]
Hi @LWChris!

Thanks for letting us know!
