### ISSUE TITLE
RPG Stack Exchange text is difficult to read

### ISSUE THREAD

**Issue by RS-David** [StylishThemes/StackOverflow-Dark#40]
![image](https://cloud.githubusercontent.com/assets/10931978/22044082/a82c98f6-dcc7-11e6-9f11-34de1b997bc8.png)
Example page, though any question on the subsite works: http://rpg.stackexchange.com/questions/93297/my-players-went-from-100-murderous-cretins-to-100-nonviolent-diplomats-how-ca

I'm not sure which approach would be best here, excluding the subsite from this style would probably be simplest (Though least rewarding for the overall goal, I'd imagine).

**Comment by Mottie** [comment]
Hi @RS-David!

Thanks for letting us know! It does not appear too difficult to include rpg.stackexchange.com in this style... so it will be available in a few minutes.
