### ISSUE TITLE
Change default background to match GitHub-Dark?

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/StackOverflow-Dark#42]
Hey @Mottie, I noticed we're still using the squares default background on pretty much all styles except GitHub Dark. What do you think about changing it? I find the new one much more pleasant to look at.

**Comment by Mottie** [comment]
Yeah, that sounds good. I'll make the new one the default in the extension I'm working on too.

<img title=":_ happy :" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif">

**Comment by Mottie** [comment]
I almost forgot about this! It's now available.
