### ISSUE TITLE
 Header-bar background opacity option

### ISSUE THREAD

**Issue by DoubleElite** [StylishThemes/StackOverflow-Dark#43]
Currently it has an opacity of 0.4 which in my personal opinion doesn't look good with the page content showing through it. Can we open up that as a Stylish option?

**Comment by Mottie** [comment]
Hi @DoubleElite!

I just noticed it too... I would rather make it have a solid background. What did you want to do as an option?

**Comment by DoubleElite** [comment]
In the Userstyle configurator there could be a numerical input field for the header bar opacity or a slider that controls it as well.

**Comment by Mottie** [comment]
Sadly userstyles.org doesn't have the ability to add a number input or a slider, it would have to be a select with options. Either way, I think a solid background color would be best.

**Comment by DoubleElite** [comment]
I agree a solid background should be default. Perhaps some select options for preset opacities if people need that. But for now removing the opacity would be good.
