### ISSUE TITLE
Top navigation issues

### ISSUE THREAD

**Issue by lukaszjurczak** [StylishThemes/StackOverflow-Dark#45]
Hi

When user is logged out the new top navigation looks like this.
![so](https://cloud.githubusercontent.com/assets/8094867/23102317/53485a60-f6a7-11e6-800f-97b3ac79aa9a.JPG)

I think we can remove 'Stackoverflow' text which is almost invisible. 
Signup button is too bright.

**Comment by Mottie** [comment]
Hi @lukaszjurczak!

Thanks for reporting this problem! Sorry for taking so long to respond & fix this issue.
