### ISSUE TITLE
Chat room comment space has white bkgd

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/StackOverflow-Dark#46]
For one of the chat rooms related to [Code Review](http://codereview.stackexchange.com/), [The 2nd Monitor](http://chat.stackexchange.com/rooms/8595/the-2nd-monitor), the bottom panel/`textarea` for writing comments has a white background. I have attached a screenshot of the same.

![stackoverflow_dark_chat_issue](https://cloud.githubusercontent.com/assets/26603964/24235157/f8e1ac5a-0fc1-11e7-9d6b-3bf91b14002b.png)

It would be nice if it is made same as those of [chat rooms](http://chat.stackexchange.com/rooms/) of other Stackexchange sites, e.g.  [Kubernetes](http://chat.stackexchange.com/rooms/55729/kubernetes) of Stackoverflow

**Comment by Mottie** [comment]
Hi @deep-programmer!

Thanks for the reporting this issue. I'll have it fixed ASAP!
