### ISSUE TITLE
Dialog for changing tracking of the next goal is white

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#47]
Steps to reproduce:

1. Be logged in
2. [Go to your profile](http://i.imgur.com/wNyCQjQ.png)
3. [Clicking on the small cog next to goal tracking](http://i.imgur.com/3JSULEw.png)
4. [The dialog that appears is white](http://i.imgur.com/rpRg0J4.png)

**Comment by Mottie** [comment]
Hi @tambry!

I no longer see that privilege popup &ndash; it gets changed to a badge popup at a certain point. Would you please share the class name that adds the white background? Or, submit a PR?

The selector name I'm seeing for the badge popup is `.css-tooltip[data-title]:hover:after`, but the background is `#474747`.

**Comment by tambry** [comment]
The class name that adds the white background seems to be `choose-tracker-menu`, which sets the `background-color` to `#FFF`.

**Comment by Mottie** [comment]
Thanks! All done!

**Comment by tambry** [comment]
That fixes it. Thanks for the quick fix!
