### ISSUE TITLE
Earned badges in the badge tracking selection dialog are white

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#48]
1. Be logged in and have at least one badge
2. [Go to your profile](http://i.imgur.com/wNyCQjQ.png)
3. [Open the badge progress tracker settings by clicking on the cog](http://i.imgur.com/OmMbXjF.png)
4. Click on the "All" tab
5. The already earned badges should be shown at the top, [unfortunately they're white](http://i.imgur.com/5IacvDO.png)

The class for the earned (white) badges is `completed`. The earned badges' background colour should be different from unearned badges' background colour. [Here's how their colour differs](http://i.imgur.com/wre8TrR.png) on the default theme.

**Comment by Mottie** [comment]
Hi @tambry!

Thanks! All fixed!
