### ISSUE TITLE
Clicking on a section in a table of contents flashes the given section as yellow-white

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#56]
1. [Navigate to the Markdown help page](https://stackoverflow.com/editing-help)
2. [Click on one of the table of contents items and it flashes yellow and then fades to white](https://zippy.gfycat.com/EquatorialCreativeBackswimmer.webm)

**Comment by Mottie** [comment]
Thanks! All the issues that you have reported have been fixed.

**Comment by tambry** [comment]
Thanks for all the fixes! I'll make sure to continue reporting once I find more :)
