### ISSUE TITLE
Tags that you have previously clicked on have a different colour

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#57]
1. Be logged in
2. [Got to the questions section](https://stackoverflow.com/questions)
3. [Modify your favourite tags](http://i.imgur.com/vJ2A6a8.png)
4. Add two new random tags you have never visited before, for example "background" and "foreground"
5. Refresh the page
6. [Now click on one of the added tags](http://i.imgur.com/kV9AmKP.png)
7. [The tag you clicked on is now blue](http://i.imgur.com/BrZaxza.png)

This behaviour is not present in the default SO style.  
The selector responsible for this is `a:visited` located [here](https://github.com/StylishThemes/StackOverflow-Dark/blob/master/stackoverflow-dark.css#L491).

**Comment by Mottie** [comment]
Hi @tambry!

Thanks! I'll look at these tomorrow.
