### ISSUE TITLE
Inbox header colour differs from the hover state of the button

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#60]
1. Be logged in
2. [Open your inbox](http://i.imgur.com/iydKcAn.png)
3. [The "Inbox" header colour differs](http://i.imgur.com/IZ6aZgp.png) from the colour of the hover state of the inbox button

On the default theme [the header colour is the same as the button's hover colour](http://i.imgur.com/vDr3JDj.png).

**Comment by Mottie** [comment]
Hi @tambry!

All fixes are now available in v2.10.0.

**Comment by tambry** [comment]
Thank you very much for all the fixes!
