### ISSUE TITLE
Wiki instructions no longer reflect the userstyles.org installation

### ISSUE THREAD

**Issue by CollinChaffin** [StylishThemes/StackOverflow-Dark#61]
The wiki at:

https://github.com/StylishThemes/StackOverflow-Dark/wiki/Install

unfortunately is no longer accurate since their site upgrade.  Now, if you are a userscript user, there is not even any way to select the parameters or what they call "advanced options" and then select to install the userscript to actually receive those settings.  Instead, it appears the parameters are only applied for their Stylish native CSS installs.  I have commented in their forums to their management however I have no idea when they will finally get around to fixing this MAJOR issue.

Until then, it almost seems that manually fashioning the install url from Github may be the only current way other than having to manually edit the script once installed.

NOTE:  Upgrades will hold their original parameter strings, so unless NEW parameters are added that did not exist in the string and if so (as in this new background update) simply figuring out that param name and manually adding it yourself in TM then re-installing works.

EDIT:  I just did this to re-confirm, adding in this case 
````
&ik-bg-url=ik-original
````
To the end of the "update" url string, then ran that entire update string in Chrome which re-installs right from the proper URL, but now adding in my case the new "original" background string, refreshed, and sure enough - all is well.

**Comment by Mottie** [comment]
Hi @CollinChaffin!

Thanks, I'll check it out soon... there is a way to add custom settings, but sadly your custom settings are not retained between sessions.

![](https://cloud.githubusercontent.com/assets/136959/26766592/a1a1125a-495a-11e7-8706-74a2b5f99fc0.gif)

**Comment by Mottie** [comment]
All done, thanks!
