### ISSUE TITLE
Problem in beta language SE

### ISSUE THREAD

**Issue by 9redhat** [StylishThemes/StackOverflow-Dark#62]
On https://portuguese.meta.stackexchange.com don't have logo but link remains...

![selection_014](https://cloud.githubusercontent.com/assets/7116826/26793103/9f06149a-4a14-11e7-8748-cc63fe79df35.png)

**Comment by Mottie** [comment]
Hi @9redhat!

Thanks for reporting this problem. It has been fixed in v2.10.0.

**Comment by 9redhat** [comment]
@Mottie can you add domain("portuguese.stackexchange.com") too, to clean up tab styling on PL site?
