### ISSUE TITLE
Developer story bugs

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#65]
1. [Go to SO](https://stackoverflow.com/)
2. Be logged in
3. [Navigate to your developer story](https://zippy.gfycat.com/LiquidGreedyAmericantoad.mp4)
4. [For traditional view bugs go to the traditional view tab](http://i.imgur.com/qfSMeOz.png)

General bugs:
* [x] [Buttons are white and have bad visibility](http://i.imgur.com/BRLxpJS.png)
  * The relevant classes are `btn` and `btn-secondary`
* [x] [The update privacy button should have no border](http://i.imgur.com/CQojvPY.png) ([see default theme](http://i.imgur.com/pAB08uM.png))
  * The class is `btn-clear`

Story view bugs:
* [x] [The dialog for adding elements to the timeline is white](http://i.imgur.com/UQ9Ig6u.png)
  * The class is `timeline-item add`
  * This element should be slightly darker than normal a `timeline-item` ([see default theme](http://i.imgur.com/HYeKbfD.png))
* [x] [Timeline items don't have backgrounds](http://i.imgur.com/PIs9pKg.png)
  * The class is `timeline-item`
* [x] [The info headers have an excessively dark background](http://i.imgur.com/t8UdqST.png)
  * The class is `header-edit-section`
* [x] [Hovering over the info headers turns them white](http://i.imgur.com/KAFh85g.png)
  * The selector is `.header-edit-section:hover`

Traditional view bugs:
* [x] [Section headers are white](http://i.imgur.com/KacpfBo.png)
  * The class is `section-header`
* [x] [The personal statement background is white](http://i.imgur.com/QH2Q2VP.png)
  * The class is `personal-statement`
* [x] [Highlighted sections' backgrounds are yellow and offer bad visibility](http://i.imgur.com/tRd5CIk.png)
  * The class that's adding the yellow is `highlight`
  * It would probably be best for all the sections to have some kind of grey background to offer better visibility over the background texture

It might be a good idea to keep this open, as there are more, but it might be worth fixing the most glaring ones first.

**Comment by Mottie** [comment]
Hi @tambry!

I'm super busy today. If you have time, I would really appreciate a pull request or two 😁.

**Comment by Mottie** [comment]
Hi @tambry!

All done, I think.

**Comment by tambry** [comment]
There are still a few smaller problems. I'll add them here and maybe try to fix a few easier ones myself.

**Comment by tambry** [comment]
Closing this for now.
