### ISSUE TITLE
Use the ISO 8601 date format

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#68]
There are many different date formats used over the world. To prevent confusion of which one is used, it'd probably be best to change the README, the wiki changelog page and other places to use the [ISO 8601 date format](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by Mottie** [comment]
Hi @tambry!

Ok, I've already been using that format in the style header. I'll start using it in the readme as well. I'll only retroactively change the last three entries. It's too much trouble to fix them all.
