### ISSUE TITLE
The grunt watch task doesn't do anything

### ISSUE THREAD

**Issue by tambry** [StylishThemes/StackOverflow-Dark#69]
When running `grunt watch` it detects that the CSS file changed, but it won't build it.

1. Run `grunt watch`
2. Change `stackoverflow-dark.css`
3. Grunt detects that it changed
4. The new built CSS file won't be output (delete the previous one to see clearly that there's no output)

**Comment by Mottie** [comment]
Hi @tambry!

I ended up removing it completely. I don't think it'd be that useful anyway.
