### ISSUE TITLE
Monokai syntax theme

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/StackOverflow-Dark#71]
Hey!

I was wondering, do you have the time to add "Monokai" to the "Syntax highlighting theme" on the USO? Or should I make a pull request?

**Comment by Mottie** [comment]
Hi @VladimirDev93!

Do you have a monokai theme for Google's [prettify](https://github.com/google/code-prettify)? If you do a PR would be awesome!

**Comment by VladimirDev93** [comment]
@Mottie No, sorry

**Comment by Mottie** [comment]
Oh found it! http://raphaelddl.github.io/google-prettify-monokai-theme/

And a bunch more! https://jmblog.github.io/color-themes-for-google-code-prettify/

I won't be able to do anything right away... too busy! 😿

**Comment by VladimirDev93** [comment]
I've just made a suggestion, not a "must-do" feature. 😸

**Comment by Mottie** [comment]
I've got it all ready to go... but I want to make sure the [license is compatible](https://github.com/RaphaelDDL/google-prettify-monokai-theme/issues/3) before I release it.

**Comment by VladimirDev93** [comment]
Woah. Last commit "Jun 24, 2015" on that repository. His dashboard is empty. I don't think that you will get a reply anytime soon.

**Comment by Mottie** [comment]
Well he was active this last March.... oh well, it's easier to ask for forgiveness than for permission 😁.

**Comment by Mottie** [comment]
Ugh... I tested it and now the colors are off...

**Comment by VladimirDev93** [comment]
Can't you use the monokai from GtiHub Dark theme?

**Comment by Mottie** [comment]
You can now... all fixed. There is a problem with userstyles.org... it's only letting me add one syntax theme option at a time. Very frustrating.

**Comment by VladimirDev93** [comment]
Works like a charm! 😸
