### ISSUE TITLE
Can you please highlight visited links?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [StylishThemes/StackOverflow-Dark#72]
Looks like now zero difference.

**Comment by Mottie** [comment]
Hi @vitaly-zdanevich!

It's not obvious, but if you go to https://userstyles.org/styles/35345/stackoverflow-dark, and click on the "Advanced Style Settings" button you'll see a bunch of customization settings. Included is an option for "visited link color":

![](https://user-images.githubusercontent.com/136959/27442204-2af9ff70-5735-11e7-83c6-973e2e80853f.png)

**Comment by Mottie** [comment]
It's really annoying that the panel isn't visible by default, and that whatever settings you choose are not remembered between sessions... I [opened an issue](https://github.com/stylish-userstyles/userstyles/issues/105#issuecomment-304691098), but it seems that no one there is very responsive.
