### ISSUE TITLE
Changing font has no effect

### ISSUE THREAD

**Issue by SuperV1234** [StylishThemes/StackOverflow-Dark#73]
Installed the theme through Stylish on Chrome - the font setting has no effect. The font here should be `"Fira Code"`, but it displays the default one:

![screenshot from 2017-06-27 18-50-07](https://user-images.githubusercontent.com/918661/27602077-7bb6b416-5b69-11e7-8b6b-98d689700782.png)

To reproduce, simply install the theme with a custom font option and refresh StackOverflow.

**Comment by Mottie** [comment]
Hi @SuperV1234!

Setting a custom font will only work if the font is installed on your system. The userstyle isn't set up to load any external fonts.

The current font stack is set up as follows:

```css
pre.prettyprint {
  font-family: "{font}", Monaco, Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

If the selected `{font}` isn't found, it will fall back to Monaco, then Consolas, etc.

**Comment by SuperV1234** [comment]
Hey @Mottie, the font is installed on my system. In fact, I managed to get it to work by replacing the css you posted above with

```
code {
  font-family: "{font}", Monaco, Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

Screenshot:

![screenshot from 2017-06-27 21-22-15](https://user-images.githubusercontent.com/918661/27608263-b5583108-5b7e-11e7-8e87-53f33deb19a8.png)

**Comment by Mottie** [comment]
Ahhh, so we just need to include a `code`  selector.

**Comment by Mottie** [comment]
Ok, try it now 😸

**Comment by SuperV1234** [comment]
Seems to work, thanks!
