### ISSUE TITLE
StackOverflow code changed

### ISSUE THREAD

**Issue by VladimirDev93** [StylishThemes/StackOverflow-Dark#74]
Oi!

![untitled](https://user-images.githubusercontent.com/12301022/27699543-f0835bb8-5cfa-11e7-83a9-7923d413909a.png)

**Comment by Mottie** [comment]
Hi @VladimirDev93!

Thanks for letting me know... it looks like there were a bunch of other changes too! I'll try to find them all and have an update available soon.

**Comment by VladimirDev93** [comment]
Hey mate, sorry again, but is this suppose to be like this?

![screenshot from 2017-06-30 14-03-01](https://user-images.githubusercontent.com/12301022/27734908-4b5ddec6-5d9d-11e7-825f-b34c191ae065.jpg)

I've tried to disable ``border-radius`` in 
```css
.s-progress-bar .-bar {
   border-radius: 0 2px 2px 0;
}
```
but it doesn't work.

**Comment by Mottie** [comment]
Yeah, I tried to fix that too... but I couldn't find the source of that "roundness". I'll give it another go soon.

**Comment by Fortunate-MAN** [comment]
any updates on this @Mottie ?

**Comment by Mottie** [comment]
Hi @Fortunate-MAN!

Not yet, I've been too busy... I'll take a look now.

**Comment by Mottie** [comment]
Hehe amazing what fresh eyes can do for you 😸

**Comment by tambry** [comment]
[Ends of the corners of the progress bars should be round](http://i.imgur.com/NeqWhnC.png).
Also [the corners at the end of the border for badge tracking are slightly golden](http://i.imgur.com/wHGEphL.png) when tracking gold badges.

**Comment by Mottie** [comment]
Hi @tambry!

Thanks! I'll look at it again.

**Comment by tambry** [comment]
The progress bar corners [are very blocky](http://i.imgur.com/3y1TJkr.png) compared to [the default](http://i.imgur.com/r7TGRNk.png).

**Comment by VladimirDev93** [comment]
@tambry it's fine to me.

I thoight you'll gonna fix this also, but I didn't want to bother you. This is the profile page of a user.

![untitled](https://user-images.githubusercontent.com/12301022/27988656-4f417918-6427-11e7-9d0c-3ad6ae3df3ad.png)

**Comment by Mottie** [comment]
> The progress bar corners are very blocky compared to the default.

It's the colors... the contrast make it seem blocky, but they added a 2px x 2px block to "round" the corner.. I could resize it to 1px x 1px... *sigh*

@VladimirDev93 I'm not always looking at SO, or other people's profiles so I might miss a few things. It's better to let me know ;)

**Comment by tambry** [comment]
Not quite the colours. The corners on the default are triangles, thus making them look round when zoomed out. I think I see how they did it. I'll try to fix it.
