### ISSUE TITLE
Code Snippet Editor

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/StackOverflow-Dark#75]
See [USO discussion](https://forum.userstyles.org/discussion/56609/stackoverflow-dark-pb-for-run-code-snipet?):

* Fix code snippet syntax highlighting (CodeMirror).
* Fix result panel text color.
* Darken option select background.

![](https://user-images.githubusercontent.com/136959/27718956-f2381a56-5d14-11e7-874a-558345f8cad0.png)

**Comment by freMea** [comment]
It could be a [stylus](https://github.com/openstyles/stylus) issue. It goes the same for the **run the code** output like [here](https://stackoverflow.com/questions/37693982/how-to-fetch-xml-with-fetch-api). The black text output is barely visible.

**Comment by Mottie** [comment]
Hi @freMea 

Yeah, Stylus doesn't watch for every DOM mutation to see if it added an iframe. I wouldn't expect it to. The solution here would be to remove the `.snippet-box-edit` definition making the result iframe dark. I still need to look at the editor when I get some time/motivation.

**Comment by the-j0k3r** [comment]
inverting the iframe was pretty much the only thing that saves corneas here, if anyone wants to have another go, please reopen this ticket and go for it. =)

**Comment by the-j0k3r** [comment]
Ive had another go, The code Snippet thingy is mostly now decent.

Ive also added a Twilight CodeMirror syntax highlighting as the default (there are no options for this, it would be huge to add this I think.

![Capture](https://user-images.githubusercontent.com/31389848/60812678-58e1c900-a192-11e9-9dbb-b92ea4c6e5ea.PNG)

This was the commit added these fixes https://github.com/StylishThemes/StackOverflow-Dark/commit/9a42a467402af3fd96b7eb27f60c0369a38708a3
