### ISSUE TITLE
AskUbuntu footer background is white

### ISSUE THREAD

**Issue by deep-programmer** [StylishThemes/StackOverflow-Dark#79]
For [AskUbuntu](https://askubuntu.com/), the bottom footer having links to other Stackexchange sites has white background

![askubuntu_bottom_footer](https://user-images.githubusercontent.com/26603964/28768134-23c560cc-75f4-11e7-8868-dd800035ebd5.png)

It would be great if its same as in other [Stackexchange](https://stackexchange.com/) sites

**Comment by Mottie** [comment]
Hi @deep-programmer!

Thanks for letting us know. All fixed now!
