### ISSUE TITLE
The style can't work as intended in both userscript and css 

### ISSUE THREAD

**Issue by ProudNoob** [StylishThemes/StackOverflow-Dark#84]
If I installed this style with [StyleRRR](https://i.imgur.com/pGwkwdH.png) then SO will look like [this](https://i.imgur.com/WiYTmAH.png). If I install vie Greasemonkey then the style works fine, but it will break my Firefox's ability to load direct image, it would just failed to load. I can't use Stylish because of bad performance and scummy practice.

**Comment by Mottie** [comment]
Hi @ProudNoob!

It sounds like a problem with StylRRR. I've never used it and it looks like it hasn't been updated in over a year. I would recommend you try [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) which is a fork of Stylish before it got scummy.

**Comment by ProudNoob** [comment]
Oh, thanks for the suggestion. Sorry to bother you with dumb, trivial thing like this.
