### ISSUE TITLE
Allsites tiles text visibility

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/StackOverflow-Dark#95]
Affected URL https://stackexchange.com/sites#

Problem is that text visibility in tiles is really low making it impossible to read. Some tiles are more affected than others.

![tiles-text](https://user-images.githubusercontent.com/31389848/32889622-8f3291d0-cac3-11e7-93d6-810583797c99.gif)

**Comment by Mottie** [comment]
Hi @the-j0k3r!

Sorry for not responding earlier, I just returned from a vacation.

I can prevent styling of the text, but there isn't an easy way to prevent the speech bubble triangle from getting styled without changing how borders are styled globally.

**Comment by the-j0k3r** [comment]
Hi @Mottie, hope you had a refreshing and fun holiday,

Whatever fixes the issue I guess ;)
